### PR TITLE
Rewrite the stdlib cmath module from C to pure Python so it can be used by Brython.

### PR DESCRIPTION
**Pull request by jonathanverner**

### CODE REVIEW

**Comment by jsbueno** [comment]
If this port gets ok, I recall seeing somewhere on CPython itself they'd prefer to have pure Python implementation of all their modules - even when there is a native code accelerated implementation.  Thus, I think our code could be offered to be placed in CPython's stdlib itself - you might open a bug there with this code, and ask for guidance.
(There is some mechanism in place for Python to pick the native code during import, so they don't need do that through special module naming as they used to do with "cstringio" and "cpickle" in Python 2.x)

**Comment by jonathanverner** [comment]
Hmm, just came across https://github.com/pybee/ouroboros which already has a pure Python implementation of cmath. It might make sense to drop my version and just use theirs... Any thoughts?

**Comment by kikocorreoso** [comment]
Wow!!! Interesting work.

Maybe it would be interesting to share some efforts between projects that are rewriting some modules in pure python (PyBee, Skult, PyPy, Brython,...).

**Comment by PierreQuentel** [comment]
@jonathanverner 

Thanks for working on this !

I have started to test the module. For this I use a tool that I have not advertised much, it's at _/tests/unittests_ : it runs a selection of modules from _Lib/test_ from the standard CPython distribution. It was broken until a few fixes last week but it can now run _test_cmath.py_, you just have to add it to the list of modules in page _tests/unittests/index.html_.

When I started the test I realized that there were things missing in Brython (eg attributes `real` and `imag` of floats, the attribute ` float_info` for module __sys__ as Kiko mentions, etc) and there are probably others, but the test also showed a few bugs in cmath, for instance in function `sqrt()`, the line

```python
ret = complex()
```
should be _after_ block

```python
ret = _SPECIAL_VALUE(x, _sqrt_special_values)
if ret is not None:
    return ret
```
otherwise in the next lines you try to set attributes to `None`.

The tests also fail with the ouroboros version so I don't know which one we should use...

**Comment by kikocorreoso** [comment]
Hi @jonathanverner @PierreQuentel ,

I have to travel a lot during the next tree weeks.

I started with the tests but right now I cannot find the time to continue with it... 😞 

It seems @PierreQuentel is already working on this.

**Comment by jonathanverner** [comment]
I am looking into the failing unittests. It seems that there are some bugs in Brython (see #667, also a weird problem with `traceback.py` where the code fails in `format` claiming '\n' is an invalid control character though I haven't been able to pinpoint the problem `'%s\n'.format(1)` works fine in the online console (but somehow fails in `traceback.py`). The implementation of `complex` (`py_complex.js`) will also need some work (equality testing, constructing complex numbers from floats, ints and other complex numbers...). I am hoping to look into that later today (or sometime this week). Once I have this fixed, I'll start investigating the other failures. 

P.S. @PierreQuentel the unittest tool is great!! I'll see if I can somehow integrate it into the continuous integration on Travis...

**Comment by PierreQuentel** [comment]
Another approach could be to test the module with CPython, ie start __test_cmath.py__ by

```python
import cmath_pure_python as cmath
```

It raises a couple of errors, which is expected, this is not an easy topic (it reminds me of the time when I did a lot of maths, a very long time ago...). Fixing these issues first - at least the most important ones - would help knowing where it's Brython that needs fixing.

**Comment by jonathanverner** [comment]
@PierreQuentel testing in CPython is actually a very good idea. I'll try that.

Speaking of math, yes, its been ages since I've done any complex analysis ;-)

**Comment by jonathanverner** [comment]
I think this is now ready to merge. 

There are three failures for the test_cmath.py unittests. Two of these also fail for my pure python implementation when run in CPython and they probably have to do with rounding errors (the errors are very small):

```
AssertionError: tan(0.01)==(0.009999666686665238,0j)!=(0.010000333346667207,0j)
```

and

```
AssertionError: sqrt0010: sqrt(complex(-1e-323, 0.0))
Expected: complex(0.0, 3.1434555694052576e-162)
Received: complex(0.0, 4.445517498970155e-162)
```
The third failure is either a bug in Brython or in the unittest implementation. The test that fails is:

```python
@requires_IEEE_754
def test_abs_overflows(self):
     # result overflows
     self.assertRaises(OverflowError, abs, complex(1.4e308, 1.4e308))
```

however, if I replace the body of the test with (seemingly equivalent)
```python
     try:
         res = abs(complex(1.4e308, 1.4e308))
         self.assertFalse(True, "SHould raise overflow")
     except OverflowError:
         pass
```

the test suddenly passes.

Anyway, if you think I should get rid of the rounding errors before merging (which I am afraid will be very hard to chase down for me), at least the changes outside of `cmath.py` should definitely be merged (they are mostly about making Brython's complex numbers behave more like Python's).

**Comment by PierreQuentel** [comment]
Many thanks @jonathanverner , very good job as usual :-)

I will see if I can fix the few remaining bugs but as it is, it passes more tests than many existing modules in the Brython distribution.

**Pull request merged**
