### PR TITLE
Support prepending to pythonpath with link rel

### PR DESCRIPTION
**Pull request by mementum**

### CODE REVIEW

**Comment by mementum** [comment]
Retriggered Travis-CI build by correcting a comment in the `unshift` line of the the pull request, no that #656 is merged (re-applies #645)

**Comment by olemis** [comment]
Very good @mementum . Should u resolve the conflicts I'll merge it myself .

Thanks for submitting the patch !

**Comment by mementum** [comment]
424 whitespace conflicts (there has been some cleaning up lately). The original patch had also some whitespacing problem and has been adjusted (with some extra whitespace cleaning too)

**Comment by olemis** [comment]
I'll merge this ... Follow up with @PierreQuentel in case further changes will be needed .

**Comment by olemis** [comment]
Thanks !

**Pull request merged**
