### PR TITLE
Update of ES docs and some fixes and updates on EN docs

### PR DESCRIPTION
**Pull request by kikocorreoso**
Please, @PierreQuentel 

Have a look to:

https://github.com/brython-dev/brython/pull/552/files#diff-cce8f561d356b49624937b88da89d6a2R108 (EN version)

https://github.com/brython-dev/brython/pull/552/files#diff-e15d00a3530865d5373a553638779216R110 (ES version)

The FR version should be updated to include the use of the `new` method instead of `JSConstructor`.

Also, I've added the `profile` option to the `brython` func options in EN and ES docs:

https://github.com/brython-dev/brython/pull/552/files#diff-9310e81df027d76b0c8f154f6a691a04R21 (EN version)

https://github.com/brython-dev/brython/pull/552/files#diff-f049835f328cca5e16bc0daa44b832cdR21 (ES version)

The *test.md* FR docs should be updated and the `profile` option should be added as above.

If everything is allright, please, merge it. If you need me to ammend whatever just comment it.

### CODE REVIEW

**Comment by PierreQuentel** [comment]
Merci Kiko !

I have pushed the translations in French and added more documentation for modules javascript (deprecated in the next version) and browser (function `load` transfered from javascript)

**Comment by kikocorreoso** [comment]
Updated the ES docs with your latest changes!!

**Comment by kikocorreoso** [comment]
BTW, I've seen that in the actual brython.info page there are some portions of the ES docs that can be seen. E.g., last part here:

http://brython.info/static_doc/en/ajax.html

http://brython.info/static_doc/es/ajax.html

In the EN version there is a script but in the ES version the script can be seen but the info is in the markdown file. Maybe it is something related with the markdown module, the files conversion, the css,... @PierreQuentel Could you have a look, please?

**Comment by PierreQuentel** [comment]
I found a bug in es/index_static.html (not for the other languages, no idea why) that removed the content of code tagged "python". The content will be updated with the next version.

**Comment by kikocorreoso** [comment]
Great!!!

Thanks.

2017-01-17 12:49 GMT+01:00 Pierre Quentel <notifications@github.com>:

**Comment by PierreQuentel** [comment]
I was too fast about the module **javascript**, we need to keep at least 2 functions: 

- one that I just added today while working with a Javascript library : `this()`, which returns the value of the Javascript keyword of the same name
- `py2js(python_source)`, which returns the Javascript code generated by Brython from the specified Python source : it may be used for precompiling (although I still don't see use cases for this)

I have changed the documentation of the module in French and English, can you do the same for Spanish ? I also made a change in the section "events" to explain how to create and dispatch events.

**Comment by kikocorreoso** [comment]
I think it is done now.

**Pull request merged**
