### PR TITLE
Fix bug in jsobjtopyobj() for kwarg objects

### PR DESCRIPTION
**Pull request by schmave**
6888c6d67b3d5b44905a09fa427a84bef2c7b304 introduced a bug that affected Python functions that take keyword arguments if the Python function was used after being called with `pyobj2jsobj()`. The way that our code ran into this situation was by storing a Python function into the value of a dictionary that was created by using a class's `__dict__` attribute. Therefore, that's what I used for the test case. If there is a less roundabout way of having `pyobj2jsobj()` be called on a function, I'd prefer to use that for the test case since that is what is really being tested, not the implementation of `__dict__` or the special handling for `dict.$jsobj` objects.

### CODE REVIEW

**Comment by schmave** [comment]
It's unclear to me if I should check in the minified files that are generated by running scripts/make_dist.py or not. Let me know what you prefer.

**Comment by jonathanverner** [comment]
I am not sure that it is good to use the result of `pyobj2jsobj` from Python code. The result is meant to be used in Javascript (where keyword arguments don't work). So I am not sure whether we should test this in our test suite. On the other hand, @schmave probably has a use case for this and the actual [change](https://github.com/brython-dev/brython/pull/824/files#diff-62b2d5f23bdf04b59d4531feb03abccb) in `js_objects.js` sort of makes sense so I think this can be merged. What do you think @PierreQuentel?

**Comment by PierreQuentel** [comment]
@schmave : thanks for the fix, it's ok for me.

@jonathanverner : in this case, the use of `pyobj2jsobj` is internal to the Brython engine, it is not used to handle a Python object from a Javascript program.

In the the test added to __issues.py__ I will change the name `js_obj_dict` to `obj_dict` to make it clear that what is handled by the Python program is a Python object.

**Comment by schmave** [comment]
Thank you both. Good point about renaming `js_obj_dict`.

**Comment by schmave** [comment]
@jonathanverner It looks to me that tests don't get run on the new code if the PR doesn't include a built version of brython.js. Am I wrong about that?

**Comment by jonathanverner** [comment]
Actually, they do run (at least they should)... The tests don't depend on brython.js but load the different javascript files which make up brython.js.

**Comment by schmave** [comment]
Ah, OK. Good to know.

**Pull request merged**
