### PR TITLE
Fixing $B.args0

### PR DESCRIPTION
**Pull request by denis-migdal**
Working on it.

### CODE REVIEW

**Comment by PierreQuentel** [comment]
I don't think the issue we were talking about is fixed

```python
class D:
    def keys(self):
        yield 'a'
    def __getitem__(self, key):
        return 7

def f(**kw):
    return kw

d = D()

assert f(**d) == {'a': 7}
```

**Comment by denis-migdal** [comment]
> I don't think the issue we were talking about is fixed

?

I do use

```javascript
for( let argname of $B.make_js_iterator(kargs) ) {

            	if( typeof argname !== "string") {
			$B.args0_old(fct, args);
			throw new Error('Non string key passed in **kargs');
		}

                result[ argname ] = $B.$getitem(kargs, argname);
```

I'll try to update master and fetch your new unit tests.

**Comment by denis-migdal** [comment]
I merged the master branch, and I pass all unit tests.

**Comment by PierreQuentel** [comment]
Yes, but I was talking about [this issue](https://github.com/brython-dev/brython/issues/2283#issuecomment-1806926797)

**Comment by denis-migdal** [comment]
> Yes, but I was talking about [this issue](https://github.com/brython-dev/brython/issues/2283#issuecomment-1806926797)

Oh I though you added the unit test.
I struggle to create a new unit test suite, so I added it to the basic test suite.

Indeed, I get the error :
```
TypeError: 'D' object is not iterable
```

But it seems to be an error in `$B.make_js_iterator()` / `keys()` method.
Indeed, shouldn't I be able to get a JS iterator like for a dict ?

There is something I do not understand.

**Comment by denis-migdal** [comment]
Okay, I think I got this.
Can you verify this commit ?

**Comment by PierreQuentel** [comment]
Perfect, I have merged the PR. Merci !

**Pull request merged**
