### PR TITLE
Remove some unnecesary imports

### PR DESCRIPTION
**Pull request by kikocorreoso**
In this commit I would like to start a work to check if there are unused imports (e.g., [here](https://github.com/brython-dev/brython/pull/527/commits/bc194cf14325772095c2b55fb295b51070918440#diff-ea4cba5d25a8cf9530ecbfa3b1b89bb9R11)) or if there is code that is unnecessary on production on a client side (e.g., [here](https://github.com/brython-dev/brython/pull/527/commits/bcf6cd35fad8910760371346b5cb4fed1ddfaa2c#diff-977f5e6deb9b6110547b2675d7c7b1feR6481)).

## Pros:

If some stuff is removed it will impact positively in the performance of the import machinery and it would make some modules/packages less dependent so a production bundle can be lighter.

## Cons:
We should be checking CPython changes for several modules on each CPython release to check if some of our changes should be updated because there is new funcionality incompatible with our changes.

@PierreQuentel Do you think it is worth the effort? I think this is something we should start analysing as people is claiming improvements in the performance and in the size of a potential production bundle of code.

Other ideas: 

* change `re` with `_jsre` when possible.
* reimplement some python widely used stuff in js.
* Remove all the `if __name__ == '__main__'` from the modules (as it has no sense to me on a client side environment).
* Mock some functionality as `argparse` (as it has no sense to me on a client side environment).
* other ideas...?

If do you think it is not a good idea just reject the PR.

### CODE REVIEW

**Comment by jonathanverner** [comment]
- removing unused imports: I am not completely against it, however only if the performance gains are noticeable; I think the cost of diverging from CPython is also nontrivial...; notably it doesn't make sense removing imports which are probably going to be imported by other stuff anyway...
- I think changing from `re` to `_jsre` is a very good idea (from my experience writing a simple tokenizer using the `re` module, it was unusably slow). 
- Removing the `if __name__ ==  '__main__'` doesn't make much sense from my point of view (the added complexity of diverging from standard python seems to outweigh the minor benefit of not executing this simple test on import; otoh this is not such a big change...)
- `argparse` might conceivably make some sense (e.g. when writing a bash console emulator...) so I would, in general, be slightly against removing it
- reimplementing some stuff in js: I guess this would be a good idea, but we should check first, where the hotspots are

In general, though, the above are only my intuitions not really backed up by any data. I think it is important to do some performance testing first to see whether the improvements are worth the effort.

As a sidenote, it would be nice if we did regular performance tests to see how different changes affect performance; possibly integrating this with the CI. I don't have much time now, but I'll see if I can find some time to work on this.

**Comment by kikocorreoso** [comment]
> removing unused imports: I am not completely against it, however only if the performance gains are noticeable; I think the cost of diverging from CPython is also nontrivial...; notably it doesn't make sense removing imports which are probably going to be imported by other stuff anyway...

In some packages there are imports that I think are not so useful in production on the client side, like `import doctest` where `doctest` depends on a lot of other packages. Maybe a switch to disallow some imports on production would be fine. OTOH, CPython is thought and works on a different environment to solve some problems. It is not possible to solve the same problems in a 'limited' platform like a browser where you have other kind of limitations (mainly network and size issues) so maybe we should start to think in some divergences.

> I think changing from re to _jsre is a very good idea (from my experience writing a simple tokenizer using the re module, it was unusably slow). 

Agree and `re` is used in a lot of modules. This is an evident example of a rewritten module in js.

> Removing the `if __name__ == '__main__'` doesn't make much sense from my point of view (the added complexity of diverging from standard python seems to outweigh the minor benefit of not executing this simple test on import; otoh this is not such a big change...)

Maybe you're right. I made some tests and it is not worth the effort in performance terms. OTOH, there is some code in some modules that is just run when called in the `if __name__ == '__main__'` and this code is not used by brython and it is more time to parse and transpile it and more size or memory usage. So, maybe a careful analysis can provide more info on this.

> `argparse` might conceivably make some sense (e.g. when writing a bash console emulator...) so I would, in general, be slightly against removing it

After have a look to the code it seems `argparse` is only called directly by `doctest`. It is easy to ignore it in a potential bundle :+1: 

> reimplementing some stuff in js: I guess this would be a good idea, but we should check first, where the hotspots are

Yes, a more careful analysis should be made.

I opened the PR just to start a discussion about this.

**Comment by jonathanverner** [comment]
> I opened the PR just to start a discussion about this.

Sure, I just wanted to give my thoughts on this and I certainly didn't mean to sound negative. I do think that performance is __very__ important and its great that you are working on improving it.

**Comment by PierreQuentel** [comment]
Thank you Kiko, I have merged these PRs : both modules are already different from the CPython version anyway.

In general, like the both of you, I am in favour of Brython-specific version only if it brings a significant performance improvement ; otherwise it's better to keep the CPython version "as is". 

Removing `if __name__ == "__main__"` won't change anything performance-wise, or marginally ; it raises other issues like the presence of `import doctest`, but such imports that require dozens of other modules but are not used by the importing script may happen anywhere in the code, not only in the `if __name__...` block.

Slightly off-topic : I have merged the `decimal` module with `_jsre`, but I don't think we should keep this module as it is today. There are two regular expression engines that are stable and well documented : the one provided by Python (in the `re` module) an the Javascript RE engine ; `_jsre` is an intermediate version, faster than `re` but not covering the whole Python re syntax. Besides `re` we should provide a `jsre` module, more limited than the current `_jsre`, that would only wrap the JS regexp engine.

**Comment by kikocorreoso** [comment]
I'm thinking in some imports that only use very specific functionality from other modules. For instance:

Today we have:
module *a.py*:
```
from collections import namedtuple
```
would import collections > _collections > _abcoll > operator > keyword > sys > heapq > itertools > reprlib > ...

Maybe a small *collections_namedtuple* module would be more efficient:
module *collections_namedtuple.py*:
```
def iskeyword(...):
    ...

def itemgetter(...):
    ....

class namedtuple:
    ....
```

This would be only for some small parts that requires this kind of functionality.

This would require a lot of work if it is implemented on the stdlib but maybe some modules on *site-packages* would do the trick and so some people could do `from collections_namedtuple import namedtuple` instead of `from collections import namedtuple`.

[Discplaimer: I'm writting at the same time I'm thinking so maybe this comment is a mess].

Maybe the idea in this comment instead of the spirit of the initial PR would be better a better. This way some people knowing what they have to do can have a smaller bundle (and can provide some ideas/modules to *site-packages*).

@PierreQuentel @jonathanverner what do you think?, ideas?

**Pull request merged**
