### PR TITLE
Enable CPython's `test_syntax.py` in CI

### PR DESCRIPTION
**Pull request by austin-schick**
This is a large PR whose changes can be split up into roughly three categories:

---

#### Get test_syntax.py running
- Update `run_tests.html` to nicely handle the CPython tests
- Fix an error where `compile()` wasn't emitting syntax errors created in the ast->js conversion process
- Fix a bug in regex that was causing doctest to never find tests to run
- Fix a JS-level crash when `exec()` producted syntactically invalid JS code

#### Fix errors caught by test_syntax.py

Some of these were nitpicky fixes just to match CPython's syntax errors, but many were real bugfixes. I think the commit messages of this PR are the best place for the list of fixes, but here are some of my favorites:

- `print(f"\\")` raised a JS error
- `A[**]` and `{**{1:2}}` raised JS errors
- `compile('lambda: None', '<test>', 'exec')` raised a JS error
- `f'{x}-{y}' = 42` ran without error

#### Add additional regression tests
- Added a few new tests to `issues.py`
- Added a test to verify that doctest discovers tests, runs them, and reports failures

---

A few more miscellaneous notes:

- I deleted just one test from `test_syntax.py` -- a test to verify that type comments are parsed correctly. This is a feature Brython doesn't currently seem to support, and it seems both obscure and difficult to add. I deleted the failing test, but I improved the related error message -- we now raise a `NotImplementedError` if a user tries to use the `ast.PyCF_TYPE_COMMENTS` flag in `compile()` or `type_comments = True` in `ast.parse`
- I made heavy use of `tests/editor.html` for debugging, and refreshed the page frequently to load new JS code. I started a habit of copying my editor contents, refreshing, and then pasting. But sometimes I'd forget to copy, and frequently losing my editor contents on refresh was bothering me, so I made a small change to the editor. It now saves its contents to local storage on edit.
- This PR also contains a fix for a very recent bug where `brython({indexedDB: false})` wasn't actually setting the `indexedDB` option to false (this was causing the CI tests to fail).

And finally:

- This PR doesn't copy over the newest version of `test_syntax.py` from the CPython repository. There are some more good bugs waiting for us over there, but I'm running out of time in my holiday break, and I think these changes are still worth merging. 
- There's a great new set of regression tests here, and I'm excited about enabling additional CPython tests in the future! Successfully passing CPython's `test_syntax`, along with its tests for `int`s, `bool`s, `set`s, `dict`s, and `list`s would be amazing.

Merci d'avance pour ta revue, Pierre !

### CODE REVIEW

**Comment by austin-schick** [comment]
I had to disable `test_web_worker` to get Travis passing consistently, and I disabled `test_aio` as well because it was causing errors when I ran testem locally in Chrome. 

I think we'd need to do some restructuring for qunit to correctly report errors in those tests that run asynchronously, and for some reason the webworker tests were throwing an `InvalidStateError` in the middle of the new syntax doctests. I ran both tests manually to make sure they produced reasonable output.

**Comment by PierreQuentel** [comment]
Thanks you very much Austin, I am genuinely impressed by the scope of this PR, it shows a deep understanding of the Brython code.
I will try to restore the missing tests, sometimes the constraint of passing the Travis CI tests seems a little too much...

**Comment by austin-schick** [comment]
Thanks Pierre! I didn't have much experience with the parser before this, but this project was a great way to get comfortable with it :)

> sometimes the constraint of passing the Travis CI tests seems a little too much...

Keeping up with CPython's changes, improving performance, fixing bugs, and keeping the tests passing all seem like important and sometimes conflicting goals! Thanks for balancing all these things.

**Comment by PierreQuentel** [comment]
In commit 3ce0dd2f8794ae974359746050a377a515b67b54 I have restored `test_webworker` and `test_aio`, the Travis CI build succeeds.

**Pull request merged**
