### PR TITLE
Adding test_struct.py

### PR DESCRIPTION
**Pull request by p-i-**
Three tests all of which currently fail

### CODE REVIEW

**Comment by olemis** [comment]
@p-i- The diff for this pull request is not just about test_struct module . It also includes changes for ... wiki pages ? Anyway I'm keen to merge test_struct but I'm not sure about the other aspects .

**Comment by olemis** [comment]
This is why I suggested to create separate branches when submitting pull requests each branch represents a different pull request . If you keep updating it over and over then things get mixed up and changes are harder to review and merge .

**Comment by p-i-** [comment]
I see! Can you merge only the first commit? Or should I redo?

**Comment by p-i-** [comment]
Ok, I created a new branch (https://github.com/brython-dev/brython/pull/267)
Then I noticed that OSX GitHub Desktop client still had the second commit in the original branch, so I reverted it. Let me know if it isn't clean and I will recreate everything from scratch.

**Comment by olemis** [comment]
Thanks @p-i- will take a look into this shortly .

**Pull request merged**
