### PR TITLE
Improvements in QUnit test suite

### PR DESCRIPTION
**Pull request by olemis**
In this pull request I've improved the QUnit test suite runner .

- It runs faster
- It prints meaningful Python tracebacks for failed test cases
- Slightly better organisation of test modules .
- Results more consistent with [tests/index.html](https://github.com/brython-dev/brython/blob/master/www/tests/index.html)
- Refactor source code a little .

@PierreQuentel I did not push it because I'd like u to please review it , could u ? Thanks in advance !

### CODE REVIEW

**Comment by olemis** [comment]
@PierreQuentel if there are no major objections I plan to merge this PR in the next few days .

**Comment by PierreQuentel** [comment]
Olemis,

I can't merge the PR - it's my fault, I took too much time to review it and it conflicts with recent commits. Sorry about that. Can you resolve the conflicts or should I do it ?

**Comment by olemis** [comment]
Don't worry . I'll do it later today

On 4/2/16, Pierre Quentel <notifications@github.com> wrote:
> Olemis,
>
> I can't merge the PR - it's my fault, I took too much time to review it and
> it conflicts with recent commits. Sorry about that. Can you resolve the
> conflicts or should I do it ?
>
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/brython-dev/brython/pull/405#issuecomment-204705686


-- 
Regards,

Olemis - @olemislc

Apache™ Bloodhound contributor
http://issues.apache.org/bloodhound
http://blood-hound.net

Brython committer
http://brython.info
http://github.com/brython-dev/brython

Blog ES: http://simelo-es.blogspot.com/
Blog EN: http://simelo-en.blogspot.com/

Featured article:

**Comment by olemis** [comment]
PR closed after I merged changes with master . The only thing that's missing is to update (auto-generated) `brython.js` file . @PierreQuentel could you please do that for me ? Thanks in advance .

**Comment by PierreQuentel** [comment]
Olemis,

Thanks for working on this. I have updated brython.js with the latest commits.

**Pull request merged**
