### PR TITLE
Improved perfomance of builtin getattr method

### PR DESCRIPTION
**Pull request by redradist**
Improve performance of `$B.$getattr` by adding global cache for object

### CODE REVIEW

**Comment by PierreQuentel** [comment]
As @schmave suggested, before submitting a PR it is better to run the test suite at _/tests/index.html_. 

The change in this PR fails to even load the page, because setting an arbitrary attribute such as `$attrscache` to a Javascript object whose "typeof" is "integer" or "string" is not possible. 

Another issue with this kind of cache is that, for instance methods, you wouldn't detect a change made to the object's class, like in

```python
class A:
  def f(self):
    return 1

a = A()
assert a.f() == 1

def g(self):
  return 2

A.f = g
assert a.f() == 2 # fails with this PR
```

Nevertheless, the idea of a cache to improve performance is good ! I introduced it in recent commits, only for methods of Brython objects that are implemented as Javascript objects of type "object", and only if the method is found in the object's class (not in one of its parents). 

For an attribute `attr`, the implementation stores
```javascript
obj.$method_cache[attr] = [method, class_function]
```

In `getattr(obj, attr)`, the cache is used this way:
```javascript
    if(obj.$method_cache &&
            obj.$method_cache[attr] &&
            obj.__class__[attr] == obj.$method_cache[attr][1]){
        // Optimisation : cache for instance methods
        // If the attribute is a method defined in the instance's class,
        // obj.$method_cache[attr] is a 2-element list [method, func] where 
        // method is the method and func is the function obj.__class__[attr]
        // at the time when the method was cached.
        // We check that the function has not changed since the method was
        // cached and if not, return the method
        return obj.$method_cache[attr][0]
    }
```

I am sure other optimizations can be done !

**Comment by redradist** [comment]
> 
> 
> As @schmave suggested, before submitting a PR it is better to run the test suite at _/tests/index.html_.
> 
> The change in this PR fails to even load the page, because setting an arbitrary attribute such as `$attrscache` to a Javascript object whose "typeof" is "integer" or "string" is not possible.
> 
> Another issue with this kind of cache is that, for instance methods, you wouldn't detect a change made to the object's class, like in
> 
> ```python
> class A:
>   def f(self):
>     return 1
> 
> a = A()
> assert a.f() == 1
> 
> def g(self):
>   return 2
> 
> A.f = g
> assert a.f() == 2 # fails with this PR
> ```
> 
> Nevertheless, the idea of a cache to improve performance is good ! I introduced it in recent commits, only for methods of Brython objects that are implemented as Javascript objects of type "object", and only if the method is found in the object's class (not in one of its parents).
> 
> For an attribute `attr`, the implementation stores
> 
> ```js
> obj.$method_cache[attr] = [method, class_function]
> ```
> 
> In `getattr(obj, attr)`, the cache is used this way:
> 
> ```js
>     if(obj.$method_cache &&
>             obj.$method_cache[attr] &&
>             obj.__class__[attr] == obj.$method_cache[attr][1]){
>         // Optimisation : cache for instance methods
>         // If the attribute is a method defined in the instance's class,
>         // obj.$method_cache[attr] is a 2-element list [method, func] where 
>         // method is the method and func is the function obj.__class__[attr]
>         // at the time when the method was cached.
>         // We check that the function has not changed since the method was
>         // cached and if not, return the method
>         return obj.$method_cache[attr][0]
>     }
> ```
> 
> I am sure other optimizations can be done !

Okay, I will check tests ... but still I think it could be done by checking `JavaScript` object type ...

**Comment by PierreQuentel** [comment]
> and page loaded and performance was improved a lot ... strange

Sorry, I meant that the page _/tests/index.html_ could not be loaded, not any page with any Brython code.

**Comment by redradist** [comment]
@PierreQuentel I have fixed issues with `boolean`, `number`, `string` ...

Issue with:
```python
class A:
  def f(self):
    return 1

a = A()
assert a.f() == 1

def g(self):
  return 2

A.f = g
assert a.f() == 2 # fails with this PR
```

Could be solved by setting runtime property to object, in such way I will check that attribute is changed nevertheless it is available in my hashtable ...

I have saw the generated code:
```javascript
"var $B = __BRYTHON__;
var _b_ = __BRYTHON__.builtins;
var $locals = $locals___main__
$locals___main__.__package__ = ""
$locals.__annotations__ = _b_.dict.$factory()
var $top_frame = ["__main__", $locals___main__, "__main__", $locals___main__]
$locals.$f_trace = $B.enter_frame($top_frame)
var $stack_length = $B.frames_stack.length;
try{
    ;$locals.$line_info = "1,__main__";if($locals.$f_trace !== _b_.None){$B.trace_line()};_b_.None;
    var module = $B.$import("browser",["console","$$window","timer"], {}, {}, true);
            $locals["console"] = $B.$getattr($B.imported["browser"], "console");
            $locals["$$window"] = $B.$getattr($B.imported["browser"], "$$window");
            $locals["timer"] = $B.$getattr($B.imported["browser"], "timer");
            _b_.None;;
    ;$locals.$line_info = "3,__main__";if($locals.$f_trace !== _b_.None){$B.trace_line()};_b_.None;
    var $A_2 = (function(){
        var $locals___main___A_2 = {__annotations__: _b_.dict.$factory()}, 
                        $locals = $locals___main___A_2, 
                        $local_name = "$locals___main___A_2"
                        $locals.$name = "A"
                        $locals.$line_info = "3,__main__";
                        var $top_frame = [$local_name, $locals,"__main__", $locals___main__]
                        $locals.$f_trace = $B.enter_frame($top_frame);
                        if($locals.$f_trace !== _b_.None){$locals.$f_trace = $B.trace_line()}
        ;$locals.$line_info = "4,__main__";if($locals.$f_trace !== _b_.None){$B.trace_line()};_b_.None;
        var f$0 = function($defaults){function f0(self){
            var $locals___main___A_2_f_3 = {},
                          $local_name = "__main___A_2_f_3",
                          $locals = $locals___main___A_2_f_3;
            var $nb_defaults = Object.keys($defaults).length
            var $len = arguments.length;
            if($len > 0 && arguments[$len - 1].$nat !== undefined){
                $locals___main___A_2_f_3 = $locals = $B.args("f", 1, {self:null}, ["self"], arguments, $defaults, null, null);
            }
            else{
                if($len == 1){
                    $locals___main___A_2_f_3 = $locals = {self:self}
                }
                else if($len > 1){$B.wrong_nb_args("f", $len, 1, ["self"])}
                else if($len + $nb_defaults < 1){$B.wrong_nb_args("f", $len, 1, ["self"])}
                else{
                    $locals___main___A_2_f_3 = $locals = {self:self}
                    var defparams = ["self"]
                    for(var i = $len; i < defparams.length; i++){$locals[defparams[i]] = $defaults[defparams[i]]}
                }
            }
            $locals.$line_info = "4,__main__"
            var $top_frame = [$local_name, $locals,"__main__", $locals___main__, f0]
            $locals.$f_trace = $B.enter_frame($top_frame)
            var $stack_length = $B.frames_stack.length;
            try{
                $locals.__annotations__ = _b_.dict.$factory()
                $locals.$name = "f"
                $locals.__class__ = $locals___main__["A"]
                $B.js_this = this;
                ;$locals.$line_info = "5,__main__";if($locals.$f_trace !== _b_.None){$B.trace_line()};_b_.None;
                var $res = 1;
                 if($locals.$f_trace !== _b_.None){$B.trace_return($res)}
                 $B.leave_frame("__main___A_2_f_3");
                 return $res;
            }
            catch(err){
                $B.set_exc(err)
                if($locals.$f_trace !== _b_.None){$locals.$f_trace = $B.trace_exception()}
                $B.leave_frame();throw err
            }
        }
        f0.$is_func = true
        f0.$infos = {
            __name__:"f",
            __qualname__:"A.f",
            __defaults__ : _b_.None,
            __kwdefaults__ : _b_.None,
            __annotations__: {},
            __dict__: _b_.dict.__new__(_b_.dict),
            __doc__: _b_.None,
            __module__ : "__main__",
            __code__:{
                          co_argcount:1,
                          co_filename:$locals___main__["__file__"],
                          co_firstlineno:4,
                          co_flags:67,
                          co_freevars: [],
                          co_kwonlyargcount:0,
                          co_name: "f",
                          co_nlocals: 1,
                          co_posonlyargcount: 0,
                          co_varnames: $B.fast_tuple(["self"]
                      )}
                  };_b_.None;
        return f0}
        $locals___main___A_2["f"] = f$0({})
        $locals___main___A_2["f"].$set_defaults = function(value){return $locals___main___A_2["f"] = f$0(value)}
        if($locals.$f_trace !== _b_.None){$B.trace_return(_b_.None)}
        $B.leave_frame()
        return $locals___main___A_2;
    }
    )();
    $A_2.__module__ = $locals___main__.__name__
    ;$locals___main__["A"] = $B.$class_constructor("A", $A_2, _b_.tuple.$factory([]),[],[])
    ;$locals___main__["A"].__doc__ = _b_.None;
    _b_.None;
    ;$locals.$line_info = "7,__main__";if($locals.$f_trace !== _b_.None){$B.trace_line()};_b_.None;
    $locals___main__["a"] = $B.$call($locals___main__["A"])();
    ;$locals.$line_info = "8,__main__";if($locals.$f_trace !== _b_.None){$B.trace_line()};_b_.None;
    if($B.$bool(!$B.$bool($B.rich_comp("__eq__",$B.$call($B.$getattr($locals___main__["a"],"f"))(),1)))){
        throw _b_.AssertionError.$factory("AssertionError")
    }
    ;$locals.$line_info = "10,__main__";if($locals.$f_trace !== _b_.None){$B.trace_line()};_b_.None;
    var g$1 = function($defaults){function g1(self){
        var $locals___main___g_4 = {},
                        $local_name = "__main___g_4",
                        $locals = $locals___main___g_4;
        var $nb_defaults = Object.keys($defaults).length
        var $len = arguments.length;
        if($len > 0 && arguments[$len - 1].$nat !== undefined){
            $locals___main___g_4 = $locals = $B.args("g", 1, {self:null}, ["self"], arguments, $defaults, null, null);
        }
        else{
            if($len == 1){
                $locals___main___g_4 = $locals = {self:self}
            }
            else if($len > 1){$B.wrong_nb_args("g", $len, 1, ["self"])}
            else if($len + $nb_defaults < 1){$B.wrong_nb_args("g", $len, 1, ["self"])}
            else{
                $locals___main___g_4 = $locals = {self:self}
                var defparams = ["self"]
                for(var i = $len; i < defparams.length; i++){$locals[defparams[i]] = $defaults[defparams[i]]}
            }
        }
        $locals.$line_info = "10,__main__"
        var $top_frame = [$local_name, $locals,"__main__", $locals___main__, g1]
        $locals.$f_trace = $B.enter_frame($top_frame)
        var $stack_length = $B.frames_stack.length;
        try{
            $locals.__annotations__ = _b_.dict.$factory()
            $locals.$name = "g"
            $B.js_this = this;
            ;$locals.$line_info = "11,__main__";if($locals.$f_trace !== _b_.None){$B.trace_line()};_b_.None;
            var $res = 2;
               if($locals.$f_trace !== _b_.None){$B.trace_return($res)}
               $B.leave_frame("__main___g_4");
               return $res;
        }
        catch(err){
            $B.set_exc(err)
            if($locals.$f_trace !== _b_.None){$locals.$f_trace = $B.trace_exception()}
            $B.leave_frame();throw err
        }
    }
    g1.$is_func = true
    g1.$infos = {
        __name__:"g",
        __qualname__:"g",
        __defaults__ : _b_.None,
        __kwdefaults__ : _b_.None,
        __annotations__: {},
        __dict__: _b_.dict.__new__(_b_.dict),
        __doc__: _b_.None,
        __module__ : "__main__",
        __code__:{
                        co_argcount:1,
                        co_filename:$locals___main__["__file__"],
                        co_firstlineno:10,
                        co_flags:67,
                        co_freevars: [],
                        co_kwonlyargcount:0,
                        co_name: "g",
                        co_nlocals: 1,
                        co_posonlyargcount: 0,
                        co_varnames: $B.fast_tuple(["self"]
                    )}
                };_b_.None;
    return g1}
    $locals___main__["g"] = g$1({})
    $locals___main__["g"].$set_defaults = function(value){return $locals___main__["g"] = g$1(value)}
    ;$locals.$line_info = "13,__main__";if($locals.$f_trace !== _b_.None){$B.trace_line()};_b_.None;
    $B.$setattr($locals___main__["A"],"f",$locals___main__["g"]);_b_.None;;
    ;$locals.$line_info = "14,__main__";if($locals.$f_trace !== _b_.None){$B.trace_line()};_b_.None;
    if($B.$bool(!$B.$bool($B.rich_comp("__eq__",$B.$call($B.$getattr($locals___main__["a"],"f"))(),2)))){
        throw _b_.AssertionError.$factory("AssertionError")
    }
    ;$locals.$line_info = "16,__main__";if($locals.$f_trace !== _b_.None){$B.trace_line()};_b_.None;
    $B.$call($B.$getattr($locals___main__["console"],"time"))('python');
    ;$locals.$line_info = "17,__main__";if($locals.$f_trace !== _b_.None){$B.trace_line()};_b_.None;
    $locals___main__["lst"] = $B.$call(_b_.list)();
    ;$locals.$line_info = "18,__main__";if($locals.$f_trace !== _b_.None){$B.trace_line()};_b_.None;
    $locals___main__["i"] = 0;
    $locals["$no_break2"] = true
    ;$locals.$line_info = "19,__main__";if($locals.$f_trace !== _b_.None){$B.trace_line()};_b_.None;
    while($B.$bool($locals["$no_break2"] && (typeof $locals___main__["i"] == "number" ? $locals___main__["i"]<10000000 : $B.rich_comp("__lt__",$locals___main__["i"],10000000)))){
        ;$locals.$line_info = "20,__main__";if($locals.$f_trace !== _b_.None){$B.trace_line()};_b_.None;
        $B.$call($B.$getattr($locals___main__["lst"],"append"))($locals___main__["i"]);
        if($locals___main__["i"] === undefined){throw _b_.NameError.$factory("name 'i' is not defined")}
        ;$locals.$line_in…"
```

But I did not understand where is new function set to object ?

**Comment by schmave** [comment]
I'm not sure if this answers your question or not, but `A.f = g` gets compiled to:

`$B.$setattr($locals___main__["A"],"f",$locals___main__["g"]);_b_.None;;`

**Comment by redradist** [comment]
> 
> 
> I'm not sure if this answers your question or not, but `A.f = g` gets compiled to:
> 
> `$B.$setattr($locals___main__["A"],"f",$locals___main__["g"]);_b_.None;;`

Thanks !!

This mean my code should reset cache for this function, because I am doing:
```javascript
$B.$setattr = function(obj, attr, value){
    setAttrCacheValue(obj, attr, null);
    ...
}
```

Something goes wrong ... but I will check )

**Comment by schmave** [comment]
Well, the setattr is called on `$locals___main__["A"]` (the class), which doesn't invalidate the cache for `$locals___main__["a"]` (an instance of that class).

**Comment by redradist** [comment]
@schmave 
> 
> Well, the setattr is called on `$locals___main__["A"]` (the class), which doesn't invalidate the cache for `$locals___main__["a"]` (an instance of that class).

I have fixed issue by introducing `dirtyAttribs` !!
Now it works )

**Comment by redradist** [comment]
@schmave @PierreQuentel 

I have fixed issue with:
```python
class A:
  def f(self):
    return 1

a = A()
assert a.f() == 1

def g(self):
  return 2

A.f = g
assert a.f() == 2 # fails with this PR
```

Take a look at my old branch ...
But I still faces with issue that by some reason `aio` cannot be imported ...
I need some help to figure out what is there reason:
https://github.com/brython-dev/brython/compare/master...redradist:perfomance/improve_perfomance_of_getattr?expand=1

**Comment by redradist** [comment]
> 
> 
> Interesting idea. It looks like you never remove items from `dirtyAttribs` though, so once a particular attribute is set, it will never be read from the cache again. This seems like a step in the right direction, though.

I have latest issue with `aio` ;)

It was due to caching functions clousers ;)

**Pull request closed without merging**
