### PR TITLE
fixes in JSObject function wrapping

### PR DESCRIPTION
**Pull request by caryoscelus**
* allow explicit `this` passing for wrapped functions
* if result is undefined, assume this being a constructor and return `this`
* save .prototype

### CODE REVIEW

**Comment by PierreQuentel** [comment]
I don't understand what this PR does. Can you explain more and give examples ?

**Comment by caryoscelus** [comment]
A bit of backstory on how i discovered the issue. I'm trying to use backbone.js with brython, so i took one example (http://backbonejs.org/#Model) and started gradually rewriting it in python. After making previous fix, i still had issues with the following code:

```python
Sidebar = JSConstructor(backbone.Model.extend({'promptColor':window.promptColor}))
```

([`backbone.Model`](https://github.com/jashkenas/backbone/blob/65952402687569aaf28abab305a14680f1f48f16/backbone.js#L394) is a constructor and [`.extend`](https://github.com/jashkenas/backbone/blob/65952402687569aaf28abab305a14680f1f48f16/backbone.js#L1874) is a function returning "subclass" constructor)

The issue was in the way `extend` is called: writing js helper function which did exactly the same, but without implicit `this` worked.

```python
Sidebar = JSConstructor(window.extend_helper(backbone.Model, {'promptColor':window.promptColor}))
```

### Issues
So the problem was in the way how `__getattribute__` was wrapping around functions.

First of all, since it always passes `self.js` as `this`, the behaviour of `apply` on wrapped function is lost (`apply` is used in `extend` on `Model`, which becomes wrapped by that time). This is fixed by replacing it with actual `this` if it is present.

Second, when function gets unwrapped as an object (i.e. not called), it becomes that `res` function and thus loses all custom attributes it originally had. I only copied `.prototype`, because it was vital for specific case (since `Model` is a "class-function"), but probably all attributes should be copied.

And lastly, if wrapped function (`Model`) is originally constructor and it is then called from constructor (one returned by `.extend` call) wrapped by JSConstructor, it does not return anything and constructed object is lost. The fix is a bit hacky as it simply returns `this` if nothing was returned.

**Comment by caryoscelus** [comment]
If that's not enough, i can put my original code with these issues later. For tests it's better to write more clear one without dependency on third-party libs though.

**Comment by PierreQuentel** [comment]
Thanks for the explanation. I must admit I don't understand all the details ;-) 

I merge the PR, if you can provide a test that would be perfect.

**Pull request merged**
