### PR TITLE
Make list_modules reusable, remove globals

### PR DESCRIPTION
**Pull request by lovasb**

### CODE REVIEW

**Comment by iansparks** [comment]
Hi @lovasb can you explain what you want to achieve here? Is the idea to automatically build the python_modules variant of the standard library (i.e. to do the dependency scanning) ? Would Django do that on every request? Where does the brython/django developer put their brython code (typically in django you have /static/.... but in brython its not 100% clear) ?

Not a maintainer for brython, just interested in brython + django. Thanks.

**Comment by lovasb** [comment]
Dear Ian,


django-brython has three different goals:

**1. Make Brython frontend development easier**: If you use this app for frontend development, then you can handle the frontend codes in the same directory structure as the server side. This has multiple advantages:
    - Don't have to start different HTTP server (eg. brython-cli --server), to serve frontend codes for Brython
    - IDE code completition works as with the server side codes
    - You can merge the client and server side codes in one directory structure, so you can share the application logic

**2. Make distribution easier**: Make reusable frontend applications easier. Because django-brython can serve Python files anywhere from PATH/PYTHON_PATH, you can easily create and distribute reusable frontend applications on the standard way as other backend packages (You don't have to create site-packages folder in your static files directory).

**3. Make production easier**: I'm working on integrate the Brython bundler to django static files ecosystem. So when you run the 'collectstatic' command during the deployment process, the django-brython app automatically bundle the frontend application code, and place to standard directory structure (into static folder). My goal is to create brython_modules.js also the same way.

The first two point is completed. Here you can find, the app documentation: https://lovasb.com/projects/django-brython/index.html
Please let me know if something isn't clear in the docs.


Bence

**Comment by iansparks** [comment]
Very cool @lovasb. I have been looking at writing unit tests for brython code. It would be useful to be able to access the unit tests in development but when packaged for production to have the tests removed. You already have 3 goals, I don't want to add to that but something to perhaps keep in mind? I would expect tests would be in their own files like test_xxxx.py (at least when using unittest.test which I know isn't everyone's favorite).

**Comment by lovasb** [comment]
Generating small size brython_modules.js is the bigges challenge in my project. Brython's bundler analyze the imports statically - also the dynamic ones. I don't have an idea, howto make dynamic imports bundling differently, so I have no choice: maintain a list (in settings.py) with the unused  packages/modules, and exclude them. With this feature you can exclude the tests also.

**Comment by lovasb** [comment]
One question: Are you testing the Brython code's business logic "only"? Or you have some solution to mock the DOM (to test the DOM malipulation methods)?

**Comment by iansparks** [comment]
I am doing this very simply for now. I am not really interested in mocking the DOM for unit tests (maybe for coverage at a later stage). It does not look too hard to make a special testrunner that can report to the console better or POST results via ajax back to the server to be recorded for CI. 

I have experimented a little with reporting results into the same DOM that the test is manipulating but I think it makes more sense to have a clean DOM so that there is no cross-contamination of tester and tested code.

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js"></script>
    <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython_stdlib.js"></script>
  </head>
<body onload="brython(1)">
</body>
</html>


<script type="text/python">
from browser import document, html
import unittest
# I also import my code here but not for this simple test. 

class Test1(unittest.TestCase):

    def test_add_span(self):
        document <= html.SPAN("Test!")
        self.assertEqual("Test!", document.select_one('span').text)

print("STARTING TESTS...")
try:
    unittest.main( failfast=True, testRunner=unittest.TextTestRunner )
except SystemExit:
    # On the event of a fail
    pass

</script>


</body>

</html>
```

Screenshot from 2020-12-03 14-43-23

**Comment by lovasb** [comment]
Dear @iansparks,

I found one solution for test running. I integrate django's test runner, with client side testing. I made a draft version in the docs with the configuration steps: https://lovasb.com/projects/django-brython/testing.html
You can try it, if you install the package from git repository.

We're far away from the original topic, so I created an issue on the projects page: https://gitlab.com/lovasb/django-brython/-/issues/1

**Pull request merged**
