### PR TITLE
Fix: `javascript.JSON.parse` crash parsing object containing null

### PR DESCRIPTION
**Pull request by eruvanos**
Using `javascript.JSON.parse` produced an error, that `null` does not contain attribute `__class__`.

### CODE REVIEW

**Comment by eruvanos** [comment]
I am not sure why, but the underscore_literals test is failing. Looks like a general issue which is not related to this code changes

**Comment by PierreQuentel** [comment]
Thanks for the PR !

Could you just change it to only include __`js_objects.js`__ and __`test_js_objects.py`__ ? The other generated files have a great risk of conflict with the latest development version because of the frenetic activity on the project ;-)

**Comment by eruvanos** [comment]
Done, I kept the `.gitignore`, is it fine?

**Comment by PierreQuentel** [comment]
That's fine, thanks !

**Pull request merged**
