### PR TITLE
Documenting IRC channel

### PR DESCRIPTION
**Pull request by p-i-**
Referencing IRC channel, renaming 'Social' to 'Community'

### CODE REVIEW

**Comment by p-i-** [comment]
I've tried to remove the second commit from the original branch `git push -f origin 4e42d5cd16b5238bd8ae137d3266269827d82ae0:test_struct`, create a new branch `git checkout -b IRC-channel`, place the second commit into the new branch `git cherry-pick 2f21041f5a792cf951827429473655b4782aedfa`, "publish" from OSX GitHub Desktop, then "pull request" from https://github.com/p-i-/brython

**Comment by olemis** [comment]
I'll leave this one to @PierreQuentel and @kikocorreoso .

**Comment by kikocorreoso** [comment]
It is ok by me but @PierreQuentel is the BDFL!!!

**Comment by PierreQuentel** [comment]
Ok for me too, thanks !

**Pull request merged**
