### PR TITLE
adding browser__debugger__ statement

### PR DESCRIPTION
**Pull request by amrdraz**
Added __debugger__ statement in the tokenizer, which will become the browser debugger statement.
This will aid in step debugging through the javascript generated brython code.

### CODE REVIEW

**Comment by amrdraz** [comment]
seems I  added the basic step back and forth in time debugger editor for tracing brython code on this branch ^^:

how should I proceed

**Comment by PierreQuentel** [comment]
Amr,

I have merged the PR, and it seems that it's something important and solving problems that have been requested for a long time. So many thanks for this ! 

Can you write some documentation to explain how to use it and what it brings to developers ? The best would be to create a file in `doc/en`, with the markdown format. You can visualise the result by running scripts/make_static_doc.py and point the browser to `/static_doc/en/<filename>.html`

**Comment by amrdraz** [comment]
are you sure you wanted both the statement and the step debugger?

Basically browsers have a keyword called debugger which is a means of inserting a breakpoint such that the chrome or firefox built in `debugger` would stop and the programer can trace.

All that I did was add `__debugger__` as a keyword to the py2js tokenizer and have it translate it to `debugger` in the outputed js code

that way when the js code is evaluated it will break in the exact line of code the brython js code was placed, allowing develoeprs to observe and step debug.

I used this feature to trace the brython code and understand how it works
then based on the some of the work I saw on roobot (since I'm building something similar) I built a step debugger that can allow my students (or anyone to step through the execution of the python code, I initially wanted to basically do bdb.py however I'm short on time so I settled for just fiering step_line events

the debugger is in tests/debugger/main.js and it's designed with callback hooks so that others can deal with it's interface (for instance in my application I already have an editor so I won't be setting up the editor in python like on the site)

I will add documentation for what I've done

it should be noted that between executing the code live and recording I went for recording for now (because I don't have the time to fix the JS-Interpreter) so currently the input instruction is not supported, although I thought of a way to do it, so I will add it later.
I also just stop on error which I will change to allow stepping through the errors

The debugger works by injecting a function after before every line in the js generated brython code, recording each frame, basically the debugging session is actually a recording of a past run.

Alternatives where the code is debugged live would include using an interpreter (which I may get to fixing one day), talizing es6 generator and yield statements (tho would require more work since yield wouldn't immediately work with function calls; or having the trace function through special errors halting the program then reruning it until the next step.

also to be pursued later when needed.

the __debugger__ statement was generally very helpful throughout all this as there was no means of inserting breakpoints in python code since it's changed at runtime to javascript so I guess it's fine to have both endeavours merged into the project, now everyone has a means of inserting breakpoints into their python code, and there's an example debugger I'll link to debugger.html somewhere I guess.

**Comment by amrdraz** [comment]
I added documentation in #269

I noticed while doing so tho that the new statement is not added to the gh-page branch (ie brython.info), tho I guess when it appears the statement update would come with it

**Pull request merged**
