### PR TITLE
Fix browser.aio.ajax headers

### LINKED ISSUE #1371: browser.aio.ajax headers broken
I've ran into some trouble with aio.ajax
version: 3.8.8 from pipy

minimal example to reproduce (by sending a post to an echo-server):
```
<!doctype html>
<html>

<head>
<meta charset="utf-8">
<script type="text/javascript" src="brython.js"></script>
<script type="text/javascript" src="brython_stdlib.js"></script>
</head>

<body onload="brython()">
<script type="text/python">
from browser import aio, ajax

url = "http://httpbin.org/post"
header = {"Content-Type": "application/x-www-form-urlencoded"}
data = {"hello": "world"}

def foo(x):
    print("ajax", x.status, x.responseText)

def main():
    ajax.post(url, headers=header, data=data, oncomplete=foo)


async def amain():
    x = await aio.post(url, headers=header, data=data)
    print("aio", x.status, x.responseText)

main()
aio.run(amain())
</script>
</body>

</html>
```
you can see from the command-line logs that the `ajax.post` function uses the correct header, but the `aio.post` doesn't.

Solution:
In www/src/libs/_aio.js line 46 there's a small typo.
`headers = _b_.dict.$to_obj(kw)` should be `headers = _b_.dict.$to_obj(kw.$string_dict[key][0])`

I do not know what other effects this change has, nor do I have experience with contributing to this project. Can someone help me further?

### PR DESCRIPTION
**Pull request by glyph**
Fixes #1371 

I just made the change described by @Tomaat in the issue description since it seemed like it might be helpful to turn the crank on the process.

### CODE REVIEW

**Comment by PierreQuentel** [comment]
It might be because of my poor English (I don't even know what "turn the crank" means here) but I suggested to the OP to submit the PR himself, as an opportunity to learn how to do it.

**Comment by glyph** [comment]
@PierreQuentel I don't know if this is an English idiom thing or a specific sub-community-that-I'm-in thing, "turn the crank" here means "to perform necessary but trivial manual work to make progress", by analogy to turning the crank on a hand-crank-powered device. (https://en.wikipedia.org/wiki/Crank_(mechanism))

Given that this is a pretty serious bug for anyone using the package, I figured that expediting a solution by providing a PR ready to press the "merge" button on would make it quicker for you to get it fixed & released.

If the goal is for the OP to learn how to do this themselves, I absolutely do not mind if you close this.

**Comment by PierreQuentel** [comment]
@glyph 
Yes it was the goal, but it will be for the next time, I have merged the PR. Thanks for this and for the explanation on "turn the crank" :-)

**Comment by glyph** [comment]
No, thank *you* @PierreQuentel ! 😄

**Pull request merged**
