### PR TITLE
Streamline the scripts in the scripts folder.

### PR DESCRIPTION
**Pull request by jonathanverner**
The idea is to have a single "master" script `manage.py` which can be used to call other scripts. It also has inbuilt documentation (which it pulls from the scripts). This series of commits:

  1. introduces the master script (which depends on the [Plumbum](https://plumbum.readthedocs.io/en/latest/) library for command-line parsing and calling system executables)
  2. rewrites some scripts so that they are callable from `manage.py` (`make_dist.py`, `make_doc.py`, ...) 
  3. moves some old scripts into `scripts/old`
  4. rewrites `make_VFS.py` to use the standard pathlib library (gets rid of a lot of `os.path....` calls)
  5. introduces a file manifest.json which lists all the files comprising the core of Brython and contains version information. 

The process to add a new script is described in [scripts/commands/README.md](https://github.com/jonathanverner/brython/blob/8a0d6400f0bee26fd15f47ff156a6abd9f632e5b/scripts/commands/README.md). Eventually, if this is merged, It would make sense to get rid of the `commands` subdirectory and have everything in scripts, but for now I am keeping this separate. 

Eventually, I'd like to add other scripts to automate e.g. making a release (bump the version, run build dist, commit, tag, push to github, npm, pypi)...

The idea behind `manifest.json` is that for some of my projects, I'd like to not include `brython.js` but include the separate scripts so that I can modify brython code with changes visible without re-generating `brython.js`. I can of course hard-code a list of scripts to include, but if there are changes in the future, I'll have to remember to add them, which is not very comfortable.

### CODE REVIEW

**Comment by jonathanverner** [comment]
@benjaminrigaud The reasoning behind calling the script `manage.py` was that it is commonly used in web development frameworks (not only Django) so it is not completely out of place. 

The reason it is not called `brython` and not located in a `bin` directory is that it is not supposed to be used by users of Brython (as opposed to developers of Brython).

**Comment by benjaminrigaud** [comment]
I understand :) Thank you. I was focused on the users side.

Do you think it is viable then to have a brython command to replace the "python -m brython" calls?

**Comment by jonathanverner** [comment]
@benjaminrigaud I think it is actually a good idea to have a `brython` command (instead of `python -m brython`) but I just haven't gotten around to implementing it :-)

**Comment by PierreQuentel** [comment]
@jonathanverner 

Sorry for the late answer, I have been busy with difficult bug fixes (829, 835, 838) these last days.

Thanks for this work, it's definitely better and cleaner than the present way of managing all the tasks for us core developers.

I merged the PR and tried to use the new scripts, but ran into a few problems:

- the core files are referenced as `MANIFEST["source"]["base"]` in __manifest.json__, but as `MANIFEST["source"]["core"]` in the scripts. This is an easy fix :-)

- more problematic, there are issues with relative imports. When I try `python manage.py dist make_dist`, I have an error message that ends with
```
  File "C:\brython\20180413\scripts\commands\dist.py", line 242, in make_dist
    vfs, num = stdlib_vfs(status_line=status)
ValueError: not enough values to unpack (expected 2, got 0)
```
The problem is caused by an `ImportError` when trying to import make_VFS in function `stdlib_vfs`. Adding a traceback in this function gives :
```
  File "C:\brython\20180413\scripts\commands\dist.py", line 52, in stdlib_vfs
    from make_VFS import create_vfs
  File "C:\brython\20180413\scripts\make_VFS.py", line 12, in <module>
    from .commands.lib.info import SRC_DIR
ImportError: attempted relative import with no known parent package
```
I tried to fix this, but got other error messages. Can you take a look ? If it's easier to fix this by putting all the scripts in __scripts/__ instead of __scripts/commands__ it's ok for me.

**Comment by jonathanverner** [comment]
@pierrequentel No worries :) I am also sorry that I won't be able to look
at this till early July; I'm walking the Camino Portugese and have very
spotty access to the internet...

**Comment by PierreQuentel** [comment]
No problem Jonathan, I use the previous version of make_dist for the moment. Enjoy the walking !

**Comment by PierreQuentel** [comment]
@jonathanverner 
For the moment I prefer to come back to the previous situation, to avoid issues like #877. When you can fix the few bugs I found, I would much prefer your version though :-)

**Pull request merged**
