### PR TITLE
Implement PEP 302 features compatible with Python 3.4

### PR DESCRIPTION
**Pull request by olemis**
Pending tasks :

  * Changes applied upon individual files , i.e. brython.js must still be put together
  * Implement [ModuleSpec type](https://www.python.org/dev/peps/pep-0451/) in new_spec function , so far a plain-old js object is used

@earney @PierreQuentel could you please get these done for me . Thanks in advance !

### CODE REVIEW

**Comment by PierreQuentel** [comment]
Olemis,

Many thanks for working on this. I would like to merge the PR but when I clone your repo, trying to run the editor with `http://localhost:8000/tests/index.html` raises an exception : 

```
Traceback (most recent call last):
  module __main__0 line 1
    import time
ImportError: time
```

Do you get the same error ?
\- Pierre

**Comment by olemis** [comment]
Yes I do . Maybe this is because (as [I said before](https://github.com/brython-dev/brython/pull/221#issue-90301210) ) brython.js has not been updated yet ? Proposed changes have been applied upon individual .js files loaded by Brython console .

Could you please rebuild brython.js file and see if it works ? I just tried `import time` statement in console and it's working as expected .

**Comment by olemis** [comment]
Oh no ! I think I know what this is about . I'll try to fix it asap .

**Comment by olemis** [comment]
@PierreQuentel at this moment there are three aspects that must be considered regarding this PR .

1. Merge with master is required
2. py_import_hooks.js must be included in every page where py_import.js script is loaded
3. There is a more serious namespace clash involving browser package , mainly because of this (executed in `Opera/9.80 (X11; Linux x86_64; U; en) Presto/2.10.289 Version/12.02`).

```python

>>> from browser import timer
>>> timer
<module 'browser.timer' from http://brython.info/src//Lib/browser/timer.py >
>>> import browser
>>> browser
<module 'browser' (built-in)>
```

... not to mention this completely different issue ...

```python

>>> import browser.__init__
Traceback (most recent call last):
  module __main__ line 2
    qs_lang, language = header.show('../')
  module exec_69 line 1
    import browser.__init__
  module browser.__init__ line 9
    WebSocket = javascript.JSConstructor(window.WebSocket)
AttributeError: no attribute WebSocket for [object Window]
>>> 
```

**Comment by olemis** [comment]
Fixed in 3e15efb . @PierreQuentel does it work for you too ? The files modified in e28c0d9 are good candidates for review as well .

p.s. I've noticed a few assertion errors in tests , but none related to the import machinery

**Comment by olemis** [comment]
The last three commits incorporate support for adding path entries in sys.path pointing to VFS files (i.e. `.vfs.js` extension) . Test cases added ! \o/

**Comment by olemis** [comment]
The last three commits incorporate support for adding path entries pointing to VFS files (i.e. `.vfs.js` extension) in sys.path . Test cases added ! \o/

**Comment by olemis** [comment]
The last three commits incorporate support for adding path entries pointing to VFS files (i.e. `.vfs.js` extension) in sys.path . Test cases added ! \o/

**Comment by olemis** [comment]
The last three commits incorporate support for adding in sys.path path entries pointing to VFS files (i.e. `.vfs.js` extension) . Test cases added ! \o/

**Comment by earney** [comment]
Awesome!

**Comment by PierreQuentel** [comment]
Olemis,

In commit 4df83b8b5540fdcf4a37180feea9d18367520b21 I have included most of the content of the PR, with a few minor bug fixes.

Many thanks for the hard work !
\- Pierre

**Comment by PierreQuentel** [comment]
Olemis,

Almost everything works now, but issue #7 has come back : can you look into this ?

**Pull request closed without merging**
