### PR TITLE
Fix class attribute resolution in argument parsing

### PR DESCRIPTION
**Pull request by moepnse**
Fix class attribute resolution in argument parsing and add a condition to check if obj supports the Thenable interface.

### CODE REVIEW

**Comment by denis-migdal** [comment]
> Fix class attribute resolution in argument parsing

Is there a case where the attribute resolution would fail as previously implemented ?

**Comment by moepnse** [comment]
Hello @denis-migdal.

Yes, in my project. I have written a small demo that reproduces the error. You can find the code below.

```python
<!DOCTYPE html>
<html>
    <head>
        <!-- Required meta tags-->
        <meta charset="utf-8">
        <title>Brython - Issue Demo 20231121</title>
        <!-- Brython -->
        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js"></script>
        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython_stdlib.js"></script>
        <script type="text/python">
from browser import console
from collections import defaultdict 


def ww_format(**kwargs):
   console.debug(kwargs)


context = defaultdict(str, {
    "oid": "0x2081"
    }
)

ww_format(**context)
        </script>
    </head>
    <body onload="brython({debug: 1});">
    </body>
</html>
```

**Comment by denis-migdal** [comment]
Oh, I see, it's the inheritance that caused the issue.

**Comment by moepnse** [comment]
How do we continue? Does a merge make sense, or do we have to rework because it has a noticeable negative impact on performance (I haven't had time to benchmark the change yet), or do you already have a better solution?

**Comment by denis-migdal** [comment]
100% compatibility with CPython is more important than performances.
I think a merge makes sense, but @PierreQuentel is the one handling merge requests.

Your fix will only impact performances when calling functions like `foo(**kwargs)`.
The "better" solution would be to change the whole implementation of Python classes in JS... so not today xD.

**Comment by moepnse** [comment]
Hello @PierreQuentel, do you have an objection to the merge request?

**Comment by PierreQuentel** [comment]
Sorry, I read the previous messages and forgot to merge at the moment, I was busy on other things...

Thanks,
Pierre

**Pull request merged**
