### PR TITLE
Support metaclass __init__ and __call__

### PR DESCRIPTION
**Pull request by mementum**
Support metaclass `__init__` if defined and if not resort to an empty `type.__init__`. This requires extracting code from `type.__new__` which was already creating the factory and returning it and using this code after having gone through `__init__`

`__new__` no longer returns a factory, but the class (or the pseudo-class-dict in brython's javascript)

This action reveals that some code is duplicated in the generic class constructor and `type.__new__`. The code in the Pull request keeps all comments to try to show why some things have been commented out and even why some other things (like the repetition of `make_mro`) could be commented out.

The extraction of the factory creation to the generic class constructor is also a prerequisite for the support of metaclass `__call__`

Tested and working. It simply moves things around and adds the call to `__init__`

### CODE REVIEW

**Comment by mementum** [comment]
#616 - one of the improvements mentioned here
#617 - even if closed for sanity, this addresses part of the missing metaclass functionality mentioned in the ticket

**Comment by mementum** [comment]
The pull request has been extended to support `__class__` in metaclasses. The existing `instance_creator` is reused if the custom `__call__` uses `super` to delegate the final action.

This allows (for example) a use case like this

```
class MetaA(type):
    def __call__(cls, *args, **kwargs):
        obj = cls.__new__(cls, *args, **kwargs)
        obj.__init__(*args, **kwargs)

        print('I am going to do something with obj after init')
        print('before returning control')
        obj.myattr = 9
        return obj


class A(metaclass=MetaA):
    def __init__(self, *args, **kwargs):
        print('A.__init__:', args, kwargs)


a = A(5, x=7)
print('a.myattr', a.myattr)
```

which outputs in the console

```
A.__init__: (5,) {'x': 7}
I am going to do something with obj after init
before returning control
a.myattr 9
```

**Comment by PierreQuentel** [comment]
Thanks for the pull request. I tested it locally, it doesn't seem to pass the test for issue #481 ; it is also the case for you ?

**Comment by mementum** [comment]
Actually the problem had been seen yesterday and some extra work is going into this pull request. The problem is that the return value of `__new__` is no longer a *factory* but the created class itself. This is not a problem for statically declared classes because they go through `$class_constructor` and the value returned by `__new__` is not that relevant because the relevant part is that `$class_constructor` returns a factory.

But for dynamically created classes (like in #418) the code goes to the function `type` which directly invokes `type.__new__` and blindly returns the value (which is no longer a factory)

This also explains why some of the code was duplicated in `type.__new__` and `$class_constructor`: to support both use cases of `type.__new__`

The solution being that `type.__new__` is relegated to the role it has to have (simply create the class) and the function `type` delegates the creation of the class to `$class_constructor`.

Some code later.

**Comment by mementum** [comment]
#481 is a pass now (i.e.: `type` now follows the regular path for class creation)

**Comment by mementum** [comment]
But some extra work will for sure go into the comings and goings of `__call__`

**Comment by mementum** [comment]
With the use case below (more might show up) failing. The instantiation of `A` works, but the instantiation of `B` in `__call__` fails with:

```
RuntimeError: TypeError: Cannot read property 'apply' of undefined
```

Which happens in `type.__call__` when trying to invoke the default factory (the one created by `$instance_creator`

```
...
return kls.$dfactory.apply(null,args)}
...
```

Use case
```
class MetaA(type):
    def __new__(meta, name, bases, dct, **kwds):
        return super().__new__(meta, name, bases, dct, **kwds)

    def __call__(cls, *args, **kwargs):
        print('MetaA.__call__', cls)
        obj = super().__call__(*args, **kwargs)

        print('I am going to do something with obj after init')
        print('before returning control')
        obj.myattr = 9
        return obj


class A(metaclass=MetaA):
    def __new__(cls, *args, **kwargs):
        print('A.__new__', cls)
        return super().__new__(cls, *args, **kwargs)

    def __init__(self, *args, **kwargs):
        print('A.__init__:', args, kwargs)


class B(A):
    pass


a = A(5, x=7)
print('a.myattr', a.myattr)

b = B(5, x=7)
print('b.myattr', b.myattr)
```

**Comment by mementum** [comment]
The last pieces should be in place

  - Making `metaclass.__init__` and `metaclass.__call__` be intrepreted as `classmethods` in `type.__getattribute__` to generate the appropriate wrapper

  - Make sure the wrapper doesn't wrap the call with the `metaclass` but with the class it is creating (for `__init__`) or with nothing for `__call__`, because the wrapping of call is the factory itself and that would generate a recursion

  - Since `__call__` must be a `classmethod` the 2nd wrapper which takes the place of `$instance_creator` wraps the appropriate class as 1st argument

**Comment by PierreQuentel** [comment]
Many thanks for this PR and the other ones, I realize it's a lot of work.

I'm not a Git expert and I'm a little lost with the branches. This one (metaclass_call) fails to pass many of the built-in tests, but the other ones (obj_init and metaclass_subclassing) pass all tests. Should I merge the 3 PRs, or only some of them and ignore the others ?

**Comment by mementum** [comment]
`obj_init` (PR #641) and `metaclass_subclassing` (PR #639) are fairly straightforward because they address a specific behavior and point in code. That makes it unlikely for them to break things outside of their own scope.

This one PR #637 adds functionality and in doing has to change the original design (`type.__new__` returns a factory) in *brython*. Such change might have consequences somewhere else.

My proposal:

  - Merge #641 and #639 
  - For this one (#637) any specific test cases to look into? The code is being used in a fairly complex metaclass concept, but that doesn't mean it will survive any scenario.

Additionally

  - It seems that PR #631 (associated to issue #632) may have been forgotten. It is also straightforward and, imho, is key in achieving a much faster loading of own code by being able to prepend to `pythonpath` via `<link rel...`.

    May be you want to have a look into it.

**Comment by mementum** [comment]
Note: the point in having a branch for each feature integration is to have the cleanest possible patch against `master`

**Comment by mementum** [comment]
Please have a look at the new test run in *Travis* after the latest commit. The line which was apparently breaking the test cases is line 38 below:

https://github.com/brython-dev/brython/blob/e20298ca0c81f3675d6a2d0bfa6668fcaca4e9b6/www/tests/brython_test_utils/unittest.py#L34-L40

I.e: The `__init__` method of the base class is being directly invoked rather than via `super`. The `metaclass_call` branch tags `__init__` and `__call__` in the *metaclass* as `classmethods` (because they are). The original code was already tagging `__new__` as `staticmethod`

Apparently, line 38 above is retrieving the right methods but they are being marked as `classmethods` with the code. `__new__` poses no problem because it is always a `staticmethod` in metaclasses and in regular classes.

Because __getattribute__ has an internal extra parameter to enable the magic in supporting `__call__`, this one is used to identify the need to mark the methods as `classmethods` or not.

The test cases with `PhantomJS` fail, but that seems to be the case with each CI integration, unless I am wrong.

**Comment by mementum** [comment]
See for example the integration of two lines in `.gitignore`: [Travis CI - Build 831](https://travis-ci.org/brython-dev/brython/builds/263471906) which also triggers the failure in `PhantomJS`

The 1st failure originates with an apparently trivial patch in an `html` file:

  - [Travis CI - Build 822] (https://travis-ci.org/brython-dev/brython/builds/261490061)
  - Commit: 4c29ad017d0b91971d195f31f6a0e18f68e28c55)

Curiously the errors in PhamtomJS complain about `init_subclass`, which is the commit in the latest 100% working build

  - [Travis CI - Build 821](https://travis-ci.org/brython-dev/brython/builds/261487285)
  - Commit: fcf588a68ed56dcdce189621f6396e6f8ed40792

Being the real mistery why Build 821 was *Ok* and Build 822 wasn't.

**Comment by mementum** [comment]
See: https://travis-ci.org/mementum/brython

The successful build is composed of:

  - Current `master`
  - The reversion of `$infos` which is breaking CI via PR #651 
  - Very minor PR #620 to allow prepending to *pythonpath*  via `<link rel=...`
  - `metaclass_call` branch PR #637 which reworks `type.__new__`, `type` and adds support for `type.__init__` and `type.__call__`

100% pass (the goal was to verify the 100% success rate of #637, this very same PR)

**Pull request merged**
