### PR TITLE
Using generate_args0 : -20% exec time???

### PR DESCRIPTION
**Pull request by denis-migdal**
**Not ready for merge.**

[Link to the old benchmark](https://github.com/brython-dev/brython/pull/2287#issuecomment-1777653838)

Using the following benchmark :
```python
from time import perf_counter as timer

def ftest1():
  pass

def ftest2(x):
  pass

def ftest3(x, y):
  pass
  
def ftest4(x, y, z):
  pass

def ftest5(*args):
  pass

def ftest6(x=0):
  pass
  
results = []

def add_result(*args):
    results.append(args)
    
N = 1000000

t0 = timer()
for i in range(N):
  ftest1()
  ftest2(i)
  ftest5(i,i)
  ftest6()
  ftest3(i, i)
  ftest6(i)
  ftest3(y=1, x=2)
  ftest4(i, i, i)

add_result('total', timer() - t0)

print(results)
```

Usage of `generateArgs0` is toggled in `js_to_ast.js` line 2107 : `const USE_PERSO_ARGS0 = true;`.

It seems execution time is reduced by 20% (from 3.15sec to 2.5sec).

Tasks remaining :

- [x] Modify the JS generation to use new parsing for all functions in order to validate against the unit tests
  - [x] Need to store the parsing function in the function infos (to not make tests during function execution).
  - [x] Will require to modify the default attributes setter (need to find where this is defined)
  - [x] Optimize function creation by having a "cache" of parsing functions.
  - [x] Pass unit tests
- [x] Optimize my output
  - [x] test unique combinations output ?
  - [x] do not use useless variables
  - [x] precompute some info ?
  - [x] $defaults also built upon function create ? (implies useless double call to getArgs0).
  - [x] Better handling of `{$kw:[{},{}]}`.
  - [x] better handling of dicts ?
  - [x] split kw args loop (first one vs the next ???) => would remove some conditions ?

### CODE REVIEW

**Comment by denis-migdal** [comment]
#2283

**Comment by denis-migdal** [comment]
Aaaaaaaand I retest and fail the firsts unit tests WTF

**Comment by PierreQuentel** [comment]
Salut Denis,

Impressive work !

I have ran the same tests as a few days ago, the results are not really different from the current development version. Do you get different results ?

```
Firefox
func with no arg -2.540
func 1 positional arg 14.163
func 2 positional args 8.686
func 3 positional args -6.418
func with *args -1.626
"def f(x=0)" called with 1 argument -10.144
"def f(x=0)" called without argument 5.420
"def f(x, y)" called with f(y=1, x=2) 9.582

Chrome
func with no arg -0.310
func 1 positional arg -1.841
func 2 positional args -3.302
func 3 positional args -2.651
func with *args -3.159
"def f(x=0)" called with 1 argument -12.951
"def f(x=0)" called without argument -3.359
"def f(x, y)" called with f(y=1, x=2) -3.423
```

**Comment by denis-migdal** [comment]
> I have ran the same tests as a few days ago, the results are not really different from the current development version. Do you get different results ?

I still haven't removed some garbage and optimized it.
The  fact I have to do `fct.$infos.args_parser()` instead of `fct.args_parser()` is a little costly.

Still, your results with Firefox are a little strange. I'll have to check on that.
Normally it is roughly the same code as before, with some lines/conditions removed so it shouldn't be slower in any cases.
Maybe I let some debug code that is costly, or something else is causing issue.

When testing each function separately the difference might be difficult to see as the browser will likely optimize some conditions when it sees that they are often "true" (which in real life isn't always the case).

I'll have to check the difference in speed between `Function(...args, code)` and `eval("function X")`, maybe `Function` is doing something I do not expect.

**Comment by denis-migdal** [comment]
It's strange, still got issue when using `fct.args_parser` instead of `fct.$infos.args_parser`, although I'm setting it like that :
```javascript
f.args_parser = f.$infos.args_parser = $B.getArgs0(...)
```

**Comment by denis-migdal** [comment]
In the unit test `issues`, it seems there are 9 different `inner8796` functions with different `$infos` object.
That's strange.

**Comment by denis-migdal** [comment]
It's strange.

When using `fct.$args_parser` it works, but when using `fct.args_parser` it doesn't.
Will push new commit.

**Comment by denis-migdal** [comment]
> I have ran the same tests as a few days ago, the results are not really different from the current development version. Do you get different results ?

I do get different results on Firefox :
```
func with no arg 6.466
func 1 positional arg -3.354
func 2 positional args -6.838
func 3 positional args -10.428
func with *args -5.830
"def f(x=0)" called with 1 argument -10.914
"def f(x=0)" called without argument -5.168
"def f(x, y)" called with f(y=1, x=2) -8.852
```
Notice that "func with no args" is +6.4% slower with my version.... when this is the same code between the 2 versions...
Still have some variables cleaning to do.

**Comment by denis-migdal** [comment]
Should now be a little more optimized for :
- [X] `(true, DEFAULTS.NONE, false, DEFAULTS.NONE, false, false, DEFAULTS.NONE, false)`
  - [ ] replace `> ARGS_POS_COUNT` and `< ARGS_POS_COUNT` by `!= ARGS_POS_COUNT`.
- [ ] `(true, DEFAULTS.SOME, false, DEFAULTS.NONE, false, false, DEFAULTS.NONE, false)`
- [ ] `(true, DEFAULTS.ALL, false, DEFAULTS.NONE, false, false, DEFAULTS.NONE, false)`
- [ ] `(false, DEFAULTS.NONE, true, DEFAULTS.NONE, false, false, DEFAULTS.NONE, false)`
- [ ] `(false, DEFAULTS.NONE, true, DEFAULTS.SOME, false, false, DEFAULTS.NONE, false)`
- [ ] `(false, DEFAULTS.NONE, true, DEFAULTS.ALL, false, false, DEFAULTS.NONE, false)`
- [ ] `(false, DEFAULTS.NONE, false, DEFAULTS.NONE, true, false, DEFAULTS.NONE, false)`
- [ ] `(false, DEFAULTS.NONE, false, DEFAULTS.NONE, false, true, DEFAULTS.NONE, false)`
- [ ] `(false, DEFAULTS.NONE, false, DEFAULTS.NONE, false, true, DEFAULTS.SOME, false)`
- [ ] `(false, DEFAULTS.NONE, false, DEFAULTS.NONE, false, true, DEFAULTS.ALL, false)`
- [ ] `(false, DEFAULTS.NONE, false, DEFAULTS.NONE, false, false, DEFAULTS.NONE, true)`

Not gonna lie, it is a little hard to optimize the output considering the number of possible combinations ( 192? ).

**Comment by denis-migdal** [comment]
### Results with old benchmark :
```
func with no arg 2.586
func 1 positional arg 1.961
func 2 positional args -7.670
func 3 positional args -7.910
func with *args -3.211
"def f(x=0)" called with 1 argument -9.006
"def f(x=0)" called without argument -1.096
"def f(x, y)" called with f(y=1, x=2) -4.124
```
Raw data :
```
NEW [('func with no arg', 0.23799999999999955), ('func 1 positional arg', 0.3119999999999976), ('func 2 positional args', 0.3130000000000024), ('func 3 positional args', 0.3259999999999934), ('func with *args', 0.42199999999999704), ('"def f(x=0)" called with 1 argument', 0.29299999999999216), ('"def f(x=0)" called without argument', 0.3610000000000042), ('"def f(x, y)" called with f(y=1, x=2)', 0.3719999999999999)]

OLD [('func with no arg', 0.23199999999999932), ('func 1 positional arg', 0.30600000000000094), ('func 2 positional args', 0.33899999999999864), ('func 3 positional args', 0.354000000000001), ('func with *args', 0.43599999999999994), ('"def f(x=0)" called with 1 argument', 0.32200000000000095), ('"def f(x=0)" called without argument', 0.3650000000000002), ('"def f(x, y)" called with f(y=1, x=2)', 0.3879999999999999)]
```

### Results with new benchmark :

```
OLD : 3.2070000000000007
NEW : 2.5
```

**-21.875% on execution time.**

### Discussion :

- Maybe I need to test on more data to have more stable results for the first benchmark ?

- Argument parsing is now up to 41.19% (`*args`) of total exec time, and down to 22% (1 pos arg) of total exec time.
The cost of `*args` is probably mainly due to the `slice()`, but I think we need the slice. Which means that other things are now responsible of 59% to 78% of total exec time. Gotta make a new test someday.

- Better handling of python dictionaries (only having to look at `$strings` or `$jsobj`) would allow quicker parsing of named arguments.

- If last argument were guaranteed to be either `null` or named argument, it'll allow some opti.

**Comment by denis-migdal** [comment]
With 10x more data :
```
func with no arg 5.683
func 1 positional arg -11.239
func 2 positional args -9.799
func 3 positional args -9.014
func with *args -10.112
"def f(x=0)" called with 1 argument -10.022
"def f(x=0)" called without argument -5.629
"def f(x, y)" called with f(y=1, x=2) -9.742
```

New version seems overall faster.
Funny that `func with no arg` is slower when this is the same code executed.

**Comment by denis-migdal** [comment]
Hum... I may have an idea to speed up processing of defaults values when kwargs are passed :
https://jsperf.app/turube

**Comment by PierreQuentel** [comment]
I have merged the PR. Thanks for the hard work Denis !

**Pull request merged**
