### PR TITLE
Overhaul of the randomness-related parts of the standard library

### PR DESCRIPTION
**Pull request by Syndace**
I noticed that the code related to the standard library's randomness was a bit messy, incomplete and potentially insecure.

First of all, I've changed the `os.urandom` implementation in `posix.js` to use a cryptographically secure random source provided by the browser, instead of `Math.random`. `Math.random` does explicitly not generate cryptographically secure randomness, thus it's usage for `os.urandom` was not spec conforming and potentially dangerous. The JavaScript API used to retrieve the randomness is [Crypto.getRandomValues()](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues), which is supported by virtually all browsers and has been supported for years. This change should not have a negative effect on Brython's browser compatibility.

The second "big" change is that I've moved the JavaScript Mersenne Twister code to the `_random` module, and have replaced the previously hand-written `random.js` with CPython's `random.py`. This is the same structure CPython uses: `random.py` contains platform-independent code, while the `_random` module is written in C and provides the Mersenne Twister. This change reduces the amount of custom JavaScript code by a lot. This change also means that the implementation of the `random` module is complete now, i.e. things like `SystemRandom`, which were not available in the hand-written module, are available now.

Third, and the initial reason I started working on this, I have added the `secrets` module of the standard library. With the above preparations done, this was as simple as copying CPython's `secrets.py`, since the module internally uses `SystemRandom`.

Other changes done as part of this pr:

- Added a bunch of files created by scripts/make_dist.py to .gitignore
- Fixed an incompatibility with CPython/PyPy regarding operator.index

### CODE REVIEW

**Comment by Syndace** [comment]
One thing missing from this pr is an update for the stdlib documentation page to say that the `secrets` module is now available and that the `random` module is not a custom js module any more. Can you give me a quick hint which files I have to change to make that happen?

**Comment by PierreQuentel** [comment]
Many thanks for the work on this module, and for the Pull Request.

I merged it, but had to cancel the merge because of 2 issues I found with the built-in test suite:

- **`test_exceptions.py`** fails with this message, and I could not find an obvious reason related to the changes you made
```
Running tests in exceptions
Traceback (most recent call last):
  File editor, line 2, in <module>
    import traceback
  File http://localhost:8000/src/Lib/traceback.py, line 569, in <module>
    _Anchors = collections.namedtuple(
NameError: name 'collections' is not defined. Did you mean: 'collections'?
<completed in 1168.00 ms (FAILED)>
```

- the test of the random module passes, but it takes a very long time (almost 10 seconds on my PC, and still more than 7 seconds with **`brython_stdlib.js`** and the indexedDB cache), and produces many warnings such as
```
http://localhost:8000/src/Lib/random.py:345: str: non-integer arguments to randrange() have been deprecated since Python 3.10 and will be removed in a subsequent version
  _warn('non-integer arguments to randrange() have been deprecated '
passed all tests...
<completed in 9782.00 ms (OK)>
```

(These warnings may be related to an incorrect implementation of warnings in Brython).

If I remember correctly, I wrote the whole random module in Javascript to make it faster than the combination of a Python module and the Javascript version of _random. Do you think there is a way to make your version (almost) as fast as the current one ?

**Comment by Syndace** [comment]
Also when we've taken care of everything, let me cleanly rebase on master before merging again.

**Comment by Syndace** [comment]
Man, git reverts are always so confusing, what happened to my branch...

**Comment by Syndace** [comment]
Okay I think I have now set up my branch so we can continue working.

**Pull request merged**
