### PR TITLE
Refactors dicts to mimic python behavior

### PR DESCRIPTION
**Pull request by JamesHutchison**
This changes the behavior of dicts to mimic python's behavior. Dicts now have their own data array consisting of key/value pairs. Objects are added to an index based on a hash value, and the array will grow when it is 75% full. Items are deleted by replacing them with a dummy object. This results in significantly faster look-ups, and also adds meaning to the hash function.

Unfortunately, a lot of existing code was coupled with the previous implementation, so the risk of introducing bugs is high. This is exasperated by the fact that I can't seem to get the unit test suite to run properly on my local machine, so there will likely be some clean-up / additional bug fixing required after merging this.

### CODE REVIEW

**Comment by glyph** [comment]
Regarding getting unit tests to run on one's local machine - one of the things I'm working on (which is blocked by #121) is a test runner that uses [Phantom JS](http://phantomjs.org); if Brython itself used this, it would make it possible to run tests on a service integrated with Github, such as Travis CI.

**Comment by earney** [comment]
Glyph,

Can you provide some of the code you are using with Phantom JS?   I would to take a look.

**Comment by glyph** [comment]
@earney - it doesn't really work yet; there are references to the work in progress on #121 though.

**Comment by gst** [comment]
> looks like it's this now:

yeah I know / have seen.

but I thought this PR / change was WIP or still waiting to be merged, so my comment, but apparently it's not so.

**Pull request closed without merging**
