### PR TITLE
Improve arguments parsing (see #2283)

### PR DESCRIPTION
**Pull request by denis-migdal**
- Currently, I pass all tests and should be faster than current implementation (though without adaptations, I'm still suboptimal, cf below).
- I only replaced `$B.args0()` function, not the other functions.
- I use the original `$B.args0()` function to raise exceptions when an error is detected.
- To be more efficient, I'd need that the last parameters always be `null`, or the array of named arguments `[{}, $B.obj_dict({"e": 32})]` (no needs for the `{$kw:[...]}` structure anymore).
- To be more efficient, I'd need some precomputed data (this prevents me from having to perform a copy at each argument parsing).
- To be more efficient, we could have different `$B.args0()` called inside functions, depending whether the function has e.g. a `*arg` parameter.

### CODE REVIEW

**Comment by PierreQuentel** [comment]
Merci Denis !

I have made a few tests to see if this version is faster than the current one. Here is the Brython script I used:
```python
from time import perf_counter as timer

def f1():
  pass

results = []

def add_result(*args):
    results.append(args)
    
N = 1000000

t0 = timer()
for i in range(N):
  f1()

add_result('func with no arg', timer() - t0)

def f2(x):
  pass

t0 = timer()
for i in range(N):
  f2(i)

add_result('func 1 positional arg', timer() - t0)

def f3(x, y):
  pass

t0 = timer()
for i in range(N):
  f3(i, i)

add_result('func 2 positional args', timer() - t0)

def f4(x, y, z):
  pass

t0 = timer()
for i in range(N):
  f4(i, i, i)

add_result('func 3 positional args', timer() - t0)

def f5(*args):
  pass

t0 = timer()
for i in range(N):
  f5(i, i)

add_result('func with *args', timer() - t0)

def f6(x=0):
  pass

t0 = timer()
for i in range(N):
  f6(i)

add_result('"def f(x=0)" called with 1 argument', timer() - t0)

t0 = timer()
for i in range(N):
  f6()

add_result('"def f(x=0)" called without argument', timer() - t0)

def f7(x, y):
  pass

t0 = timer()
for i in range(N):
  f7(y=1, x=2)

add_result('"def f(x, y)" called with f(y=1, x=2)', timer() - t0)

print(results)
```

Then I copied the result from the browser console to this Python script, replacing "old" by the values with the current implementation and "new" by those with your version.

```python
old = ... # starts with "[('func with no arg', ///

new = ... # idem

for old_res, new_res in zip(old, new):
    diff = 100 * (new_res[1] - old_res[1]) / old_res[1]
    print(old_res[0], f'{diff:.3f}')
```

I did the tests on Firefox and Chrome.

Can you run them (or something more complete) on your machine ? We will share the results we get before making a conclusion.

**Comment by denis-migdal** [comment]
Here my results on Firefox :
````
func with no arg 4.211
func 1 positional arg -0.309
func 2 positional args -5.246
func 3 positional args -11.082
func with *args 1.577
"def f(x=0)" called with 1 argument -2.172
"def f(x=0)" called without argument 10.233
"def f(x, y)" called with f(y=1, x=2) -2.319
````

When called without arguments or with only `*arg`, I'm slower, else I'm faster.
The more the function has positional argument, the more I'm faster.

Note that I'm doing some extra operations due to the fact I do not have the arguments and pre-computed data like I'd need. I can remove the copy of arguments and see the results. Then I could also see what happens when I remove the copy of default named values.

I can also add some shortcuts if needed. But the best way would be to have different functions for different simple cases to remove lot of conditions/checks.

**Comment by denis-migdal** [comment]
Did a new version without the initial argument copy (a "h4ck" I did as I didn't got input data like I'd like).
I'll push a new commit on my git.

Without the argument copy I got :
````
func with no arg -20.888
func 1 positional arg -37.355
func 2 positional args -38.275
func 3 positional args -34.712
func with *args -31.569
"def f(x=0)" called with 1 argument -37.934
"def f(x=0)" called without argument -35.671
"def f(x, y)" called with f(y=1, x=2) -29.610
````

Note: The second time I executed the old version, it was slower, if I compare to the first time I executed old :
````
func with no arg 3.171
func 1 positional arg -14.279
func 2 positional args -18.898
func 3 positional args -20.716
func with *args -5.872
"def f(x=0)" called with 1 argument -9.660
"def f(x=0)" called without argument 0.763
"def f(x, y)" called with f(y=1, x=2) -10.620
````

So I'm almost faster everywhere, and still have some parts I can optimise if data aren't precomputed.
To compare to my first version (that did the argument copy) :
````
func with no arg -0.998
func 1 positional arg -14.014
func 2 positional args -14.408
func 3 positional args -10.835
func with *args -7.333
"def f(x=0)" called with 1 argument -7.654
"def f(x=0)" called without argument -8.591
"def f(x, y)" called with f(y=1, x=2) -8.499
````


Raw data :
````
New

[('func with no arg', 0.28461999999999854), ('func 1 positional arg', 0.4071599999999993), ('func 2 positional args', 0.4400200000000005), ('func 3 positional args', 0.4557599999999997), ('func with *args', 0.5425000000000004), ('"def f(x=0)" called with 1 argument', 0.4081400000000013), ('"def f(x=0)" called without argument', 0.45931999999999995), ('"def f(x, y)" called with f(y=1, x=2)', 0.5906800000000008)]
<completed in 3618.60 ms (OK)>

Old

[('func with no arg', 0.2731200000000005), ('func 1 positional arg', 0.40842000000000134), ('func 2 positional args', 0.464380000000002), ('func 3 positional args', 0.5125599999999988), ('func with *args', 0.5340800000000012), ('"def f(x=0)" called with 1 argument', 0.4172000000000011), ('"def f(x=0)" called without argument', 0.4166799999999995), ('"def f(x, y)" called with f(y=1, x=2)', 0.6047000000000011)]
<completed in 3671.22 ms (OK)>

New no args copy

[('func with no arg', 0.2817799999999995), ('func 1 positional arg', 0.3501000000000012), ('func 2 positional args', 0.37661999999999995), ('func 3 positional args', 0.4063799999999995), ('func with *args', 0.5027200000000001), ('"def f(x=0)" called with 1 argument', 0.3769000000000009), ('"def f(x=0)" called without argument', 0.4198599999999999), ('"def f(x, y)" called with f(y=1, x=2)', 0.5404800000000023)]

Old (bis)

[('func with no arg', 0.35618000000000904), ('func 1 positional arg', 0.5588599999999957), ('func 2 positional args', 0.6101599999999934), ('func 3 positional args', 0.6224400000000117), ('func with *args', 0.7346399999999988), ('"def f(x=0)" called with 1 argument', 0.6072600000000108), ('"def f(x=0)" called without argument', 0.6526799999999895), ('"def f(x, y)" called with f(y=1, x=2)', 0.7678399999999925)]
````

**Comment by denis-migdal** [comment]
Replaced `??` by conditions to speed up execution (cf previous commit).

Noticed that Brython dict can have `.$jsobj` or `$.strings` equal to `null` or `undefined`. I argue that :
- this shouldn't be the case, it should be either `undefined` or an object, OR `null` or an object, but not the 3 (this would remove one condition check).
- `.$strings` should be removed, and only `.$jsobj` should be used ? (this would remove one condition).

I'll tackle down the copy when handling named argument, and I'll stop here.
Now I seems almost always faster than current implementation (results varies a little from one execution to another).

And again, if I get access to some input/precomputed data I want, we can go faster.


Current results :
````
func with no arg -0.921
func 1 positional arg -18.808
func 2 positional args -19.865
func 3 positional args -22.549
func with *args -9.088
"def f(x=0)" called with 1 argument -16.514
"def f(x=0)" called without argument -2.689
"def f(x, y)" called with f(y=1, x=2) -8.063
````

**Comment by denis-migdal** [comment]
New results by removing the copy when having named arguments.
````
func with no arg -0.466
func 1 positional arg -21.398
func 2 positional args -24.025
func 3 positional args -25.326
func with *args -12.336
"def f(x=0)" called with 1 argument -18.077
"def f(x=0)" called without argument -6.444
"def f(x, y)" called with f(y=1, x=2) -19.934
````

Compared to "new args no copies" :
````
func with no arg 1.675
func 1 positional arg -2.588
func 2 positional args -2.634
func 3 positional args -4.966
func with *args -4.611
"def f(x=0)" called with 1 argument -2.871
"def f(x=0)" called without argument 0.272
"def f(x, y)" called with f(y=1, x=2) -10.716
````
In fact, only the last line matters, other are due to RNG it seems.


If I had a list of all default values (even the named ones) + some precomputed boolean/offset/indexes, I could be even faster.

**Comment by denis-migdal** [comment]
Mmmm... may have an idea to speed up things a little more.
Gotta test it tomorrow.

**Comment by denis-migdal** [comment]
I tried to test a `def f8(x, *, y=2)` called with `f8(i)`, and to optimize it a little :
- results are too unstable (varies a lot between executions).
- we could remove a big part of the cost by pre-computing an array of named only args default values.

I have 3 more tests to do.

**Comment by denis-migdal** [comment]
In previous commit, optimized a little looping over named arguments.

````
func with no arg -0.796
func 1 positional arg -16.483
func 2 positional args -17.997
func 3 positional args -18.911
func with *args -7.725
"def f(x=0)" called with 1 argument -14.672
"def f(x=0)" called without argument -3.643
"def f(x, y)" called with f(y=1, x=2) -28.930
````

Last test seems faster (expected). Other tests seems slower than previous tests, but likely be due to RNG (only 1-2% diff).
Compared to "args no copies" :
````
func with no arg -2.647
func 1 positional arg 0.183
func 2 positional args 2.278
func 3 positional args 1.969
func with *args -1.826
"def f(x=0)" called with 1 argument -1.804
"def f(x=0)" called without argument 0.667
"def f(x, y)" called with f(y=1, x=2) -18.084
````

**Comment by denis-migdal** [comment]
I replaced the `in` when searching for default values in named parameters, by a `.values()`.
`.values()` is costly but can be precomputed. Loops is normally faster :
````

OLD : [('func with no arg', 0.2877200000000002), ('func 1 positional arg', 0.45667999999999864), ('func 2 positional args', 0.5056799999999981), ('func 3 positional args', 0.5467200000000005), ('func with *args', 0.5782200000000017), ('"def f(x=0)" called with 1 argument', 0.4532000000000025), ('"def f(x=0)" called without argument', 0.4583999999999975), ('"def f(x, y)" called with f(y=1, x=2)', 0.6454399999999971)]

NEW LOOP...
[('func with no arg', 0.2667400000000004), ('func 1 positional arg', 0.3357800000000015), ('func 2 positional args', 0.3716399999999993), ('func 3 positional args', 0.38705999999999996), ('func with *args', 0.4753600000000002), ('"def f(x=0)" called with 1 argument', 0.3509600000000006), ('"def f(x=0)" called without argument', 0.4158200000000001), ('"def f(x, y)" called with f(y=1, x=2)', 0.4833199999999991)]


func with no arg -7.292
func 1 positional arg -26.474
func 2 positional args -26.507
func 3 positional args -29.203
func with *args -17.789
"def f(x=0)" called with 1 argument -22.560
"def f(x=0)" called without argument -9.289
"def f(x, y)" called with f(y=1, x=2) -25.118
````

When comparing the the previous results :
````
PREVIOUS NEW : [('func with no arg', 0.27431999999999945), ('func 1 positional arg', 0.35074000000000183), ('func 2 positional args', 0.3851999999999993), ('func 3 positional args', 0.4143800000000013), ('func with *args', 0.4935400000000012), ('"def f(x=0)" called with 1 argument', 0.37010000000000076), ('"def f(x=0)" called without argument', 0.42266000000000226), ('"def f(x, y)" called with f(y=1, x=2)', 0.4427399999999988)]

func with no arg -2.763
func 1 positional arg -4.265
func 2 positional args -3.520
func 3 positional args -6.593
func with *args -3.684
"def f(x=0)" called with 1 argument -5.172
"def f(x=0)" called without argument -1.618
"def f(x, y)" called with f(y=1, x=2) 9.166
````
Strangely I seem slower (but was tested a moment ago, so it might be explained by other factors).
I'm still letting that as I think it'd be faster once the `.values()` is precomputed (this action costs a lot).

**Comment by denis-migdal** [comment]
New commit should be faster **BUT WON'T WORK** as python authorizes `def foo(*, x=4, y)` (therefore commit doesn't pass the tests).
Could be used if, and only if, named-only arguments are re-ordered (is this an issue ?) to ensure named-only arguments with default values are put lasts.

Previous commit shouldn't had passed the test too, that's strange.

I'll make a last commit of another version and that'd be all.


Also just though of it, but is there a guarantee on the order of elements inside `locals` ?
Indeed, as I fill named-only default arguments last they won't be in the same order as the functions parameters when building the `locals`... But that'd be very strange (and dirty) to rely on such order.

**Comment by coproc** [comment]
> `def foo(*, x=4, y)`
> Could be used if, and only if, named-only arguments are re-ordered (is this an issue ?) to ensure named-only arguments with default values are put lasts.

Hm, you mean if the above function definition could internally be rewritten to `def foo(*, y, x=4)` s.t. all _required_ keyword-only arguments come before the _optional_ keyword-only arguments? Actually I think such two definitions are equivalent, as long as the order of the optional keyword-only arguments (i.e. the order of the expressions for the default values) is not changed. To make sure this should be discussed with Python language experts, e.g. on [Python-list](https://mail.python.org/mailman/listinfo/python-list).

**Comment by denis-migdal** [comment]
Last version :
````
OLD [('func with no arg', 0.27664000000000044), ('func 1 positional arg', 0.4181600000000003), ('func 2 positional args', 0.47767999999999766), ('func 3 positional args', 0.513440000000001), ('func with *args', 0.5263400000000011), ('"def f(x=0)" called with 1 argument', 0.4222799999999989), ('"def f(x=0)" called without argument', 0.4665599999999994), ('"def f(x, y)" called with f(y=1, x=2)', 0.6185599999999987)]

NEW [('func with no arg', 0.2674399999999997), ('func 1 positional arg', 0.3399000000000001), ('func 2 positional args', 0.38480000000000025), ('func 3 positional args', 0.38721999999999923), ('func with *args', 0.5020400000000009), ('"def f(x=0)" called with 1 argument', 0.35418000000000127), ('"def f(x=0)" called without argument', 0.4048799999999986), ('"def f(x, y)" called with f(y=1, x=2)', 0.4310200000000002)]

func with no arg -3.326
func 1 positional arg -18.715
func 2 positional args -19.444
func 3 positional args -24.583
func with *args -4.617
"def f(x=0)" called with 1 argument -16.127
"def f(x=0)" called without argument -13.220
"def f(x, y)" called with f(y=1, x=2) -30.319
````

I think there are no doubts that this version is way faster than current implementation.
Note that this is the gain of perfs on the whole function call. A -30% total execution time is 1.43x faster.
For one argument, if I recall, it was 38% of total execution time. -18% total execution time mean a x2.1 speed increase on the parsing function.

@PierreQuentel What should be the next step ?

**Comment by PierreQuentel** [comment]
Super boulot Denis !

I could reproduce these figures, and the built-in speed test (_/speed/make_report.html_) also shows a significant improvement for most of the tests. I have merged the Pull Request.

**Comment by PierreQuentel** [comment]
I just found a small bug in error reporting:
```python
def f(x, y=0):
  print(x, y)

f()
```

The error message should be
```
TypeError: f() missing 1 required positional argument: 'x'
```

but with the new version it is
```
TypeError: f() missing 2 required positional arguments: 'x' and 'y'
```

Could you fix this by another PR ?

Thanks

**Comment by PierreQuentel** [comment]
Le boulet... j'aurais dû vérifier, je pensais que c'était dans la suite de tests. Corrigé dans le commit c698e7c5d040dbd35e65ecc7ed483ca0f9a80a42.

Encore merci c'est super ce que tu as fait !

**Pull request merged**
