### PR TITLE
Rewrite cli interface

### PR DESCRIPTION
**Pull request by ennec-e**
Use subcommands for better options delineating
```
[~]$ brython-cli 
usage: brython-cli [-h] [--version] {install,init,update,add_package,make_package,make_modules,start_server,make_dist,make_file_system} ...

optional arguments:
  -h, --help            show this help message and exit
  --version             Brython version number

subcommands:
  {install,init,update,add_package,make_package,make_modules,start_server,make_dist,make_file_system}
                        Use --help with any subcommand to see more details
    install (init)      Install Brython in an empty directory
    update              Update Brython scripts (brython.js, brython_stdlib.js)
    add_package         Add already-installed Python package to Brython project
    make_package        Make a browser loadable Python package script
    make_modules        Create brython_modules.js with all the modules used by the application
    start_server        Start development server
    make_dist           Make a Python distribution
    make_file_system    Make a virtual file system

```

```
[~]$ brython-cli add_package --help
usage: brython-cli add_package [-h] [--dest-dir DEST_DIR] package

Add an already-installed, pure-Python package from current CPython environment into current Brython project's ./Lib/site-packages

positional arguments:
  package              package name

optional arguments:
  -h, --help           show this help message and exit
  --dest-dir DEST_DIR  Optionally specify alternate destination dir
```

```
[~]$ brython-cli make_package --help
usage: brython-cli make_package [-h] [--src-dir SOURCE_DIR]
                                [--exclude-dirs EXCLUDE_DIR [EXCLUDE_DIR ...]] [-o OUTPUT_PATH]
                                package_name

Make a loadable {package_name}.brython.js package file from regular python package

positional arguments:
  package_name          name used to import this package. as in (`import {package_name}`)

optional arguments:
  -h, --help            show this help message and exit
  --src-dir SOURCE_DIR  package source dir (defaults to current dir)
  --exclude-dirs EXCLUDE_DIR [EXCLUDE_DIR ...]
                        directories under src-dir to exclude
  -o OUTPUT_PATH, --output-path OUTPUT_PATH
                        package file output path (defaults to {package_name}.brython.js in source dir)
```

This structure change is (hopefully) a improvement to the current cli interface structure. 
Subcommands designate *actions*. And options are used to pass parameters to those actions.

Do give it a try. Open to to suggestions.
We can discuss here if there's anything you'd like changed and if you'd like to see this merged eventually.  
🤞

### CODE REVIEW

**Comment by ennec-e** [comment]
@PierreQuentel Can you take a look at this sometime?

Just want to know if it might actually be of interest, before I prioritise cleaning up the code and working on it some more.  
[This commit] already does implement ~~most~~ all of what's shown above, so you can even try it right away. 

[This commit]: https://github.com/brython-dev/brython/pull/1912/commits/03185681954ba4fe29797d5ecdcc2ed109abe79c

**Comment by PierreQuentel** [comment]
@ennec-e 

Thanks for the proposal, and sorry for the late answer, I was almost full time on the major rewriting of the Brython engine.

I agree that this version is an improvement to the current CLI interface, but it is backwards-incompatible. Could it be possible, at least temporarily, to have a warning if a user accustomed to the current version uses the old syntax (eg `--add_package` instead of `add_package`) ?

**Comment by ennec-e** [comment]
Updated, with backwards compatibility. 

```
[~]$ brython-cli 
usage: brython-cli [-h] [--add_package ADD_PACKAGE] [--install] [--make_dist] [--make_package MAKE_PACKAGE]
                   [--make_file_system MAKE_FILE_SYSTEM] [--modules] [--reset] [--server [SERVER]] [--update] [--version]
                   {install,init,update,add_package,make_package,make_modules,start_server,make_dist,make_file_system} ...

options:
  -h, --help            show this help message and exit
  --add_package ADD_PACKAGE
                        Add an already-installed, pure-Python package from current CPython environment into current Brython
                        project's ./Lib/site-packages
  --install             Install Brython in an empty directory
  --make_dist           Make a Python distribution
  --make_package MAKE_PACKAGE
                        Make a loadable Python package
  --make_file_system MAKE_FILE_SYSTEM
                        Make a virtual file system
  --modules             Create brython_modules.js with all the modules used by the application
  --reset               Reset brython_modules.js to stdlib
  --server [SERVER]     Start development server
  --update              Update Brython scripts
  --version             Brython version number

subcommands:
  {install,init,update,add_package,make_package,make_modules,start_server,make_dist,make_file_system}
                        Use --help with any subcommand to see more details
    install (init)      Install Brython in an empty directory
    update              Update Brython scripts (brython.js, brython_stdlib.js)
    add_package         Add already-installed Python package to Brython project
    make_package        Make a browser loadable Python package script
    make_modules        Create brython_modules.js with all the modules used by the application
    start_server        Start development server
    make_dist           Make a Python (PyPI) distribution
    make_file_system    Make a virtual file system
```

Also prints deprecation warning on use of options style commands.
```
DeprecationWarning: Options style primary args may be deprecated soon. Please use subcommands instead (see '--help')
```

**Comment by PierreQuentel** [comment]
Many thanks for the PR ! I have merged it, then slightly changed the management of "old style" commands : instead of using warning.warn (the deprecation message didn't show, probably because of the default warning filters), I have added a "print" with a message specific to each command, such as
```
Option --install will be deprecated in the next release. Please use `brython-cli install` instead (see '--help')
```

I will also update the documentation with the new style CLI interface.

**Pull request merged**
