### PR TITLE
Updating README.md files

### PR DESCRIPTION
**Pull request by Kalbra**
Removes spaces at the readme html examle. Changes the markdown code type from xml to html.
The same changes have been made for the document README_pt_br.md.
Also the README.md in the npm folder was updated.

### CODE REVIEW

**Comment by PierreQuentel** [comment]
@Kalbra Thanks for the PR, it looks good to me but why did you first change the language to html, then back to xml ?

**Comment by Kalbra** [comment]
@PierreQuentel Strange, because when I looked into the changes there isn't a xml at the readme's.
Maybe the type in the commit confused you. The form sould be a from, so `changing the codetype from xml to html`.
But if you mean a other thing, please let me now, because currently I don't know what to change.

**Comment by PierreQuentel** [comment]
In the current version, HTML page examples use the tag ```xml.

```xml
    <html>

        <head>
            <script type="text/javascript" src="/path/to/brython.js"></script>
        </head>

        <body onload="brython()">

            <script type="text/python">
            from browser import document, alert

            def echo(event):
                alert(document["zone"].value)

            document["mybutton"].bind("click", echo)
            </script>

            <input id="zone"><button id="mybutton">click !</button>

        </body>

    </html>
```

In the first commit in the PR ([d915128](https://github.com/brython-dev/brython/pull/1882/commits/d9151284168ae5d674c45b860fee19ff375c79f1)), it is changed to ```html (which is slightly better, since Python code has some highlighting).

```html
<html>

    <head>
            <script type="text/javascript" src="/path/to/brython.js"></script>
    </head>

    <body onload="brython()">

        <script type="text/python">
        from browser import document, alert

        def echo(event):
            alert(document["zone"].value)

        document["mybutton"].bind("click", echo)
        </script>

        <input id="zone"><button id="mybutton">click !</button>

    </body>

</html>
```

But then in the 3rd commit [f0323af](https://github.com/brython-dev/brython/pull/1882/commits/f0323afdeff9666e0d9b7215aa7aaa9bb950a66e), the prefix is changed back to ```xml.

**Comment by Kalbra** [comment]
I don't know what you mean because at https://github.com/brython-dev/brython/pull/1882/commits/f0323afdeff9666e0d9b7215aa7aaa9bb950a66e the xml is changed to html and not the other way around.
The xml stands on the diff because it is not the orginal README.md, but the README.md in the npm folder. 
So https://github.com/brython-dev/brython/pull/1882/commits/f0323afdeff9666e0d9b7215aa7aaa9bb950a66e just copies the content of [README.md](/brython-dev/brython/blob/master/README.md) to [npm/README.md](https://github.com/brython-dev/brython/blob/master/npm/README.md)

**Comment by PierreQuentel** [comment]
My mistake, sorry... I didn't notice you had changed README.md in two different locations.
Thanks !

**Comment by Kalbra** [comment]
No problem

**Pull request merged**
