### PR TITLE
Fix issue #2311

### PR DESCRIPTION
**Pull request by moepnse**
Restore JavaScript's strict mode and fix reference errors.

### CODE REVIEW

**Comment by PierreQuentel** [comment]
Sorry @moepnse , I can't merge this PR. With JSHint (a tool that checks Javascript files) I see that there are a few other places where variables are not declared, which causes errors in strict mode. For instance
```
Brython 3.12.0 on Netscape 5.0 (Windows)
Type "help", "copyright", "credits" or "license" for more information.
>>> float.fromhex('66')
Traceback (most recent call last):
JavascriptError: assignment to undeclared variable save_pos
>>> 
```
If we can remove all the occurrences of undeclared variables with such a tool, what will be the point in applying strict mode ?

**Comment by denis-migdal** [comment]
> what will be the point in applying strict mode ?

Strict mode enables some optimizations during runtime.

It also avoid silent errors, so should be at least used during development.

**Comment by PierreQuentel** [comment]
In commit e2311f9d4a5379d51aa9054e7d6ccf5e929cdd09 I have added a new script, **`/scripts/apply_jshint.py`**, that detects all the "undeclared variable name" warnings produced by JSHint on the scripts in /src and /src/libs, and I have fixed all these warnings.

**Comment by denis-migdal** [comment]
> In commit [e2311f9](https://github.com/brython-dev/brython/commit/e2311f9d4a5379d51aa9054e7d6ccf5e929cdd09) I have added a new script, **`/scripts/apply_jshint.py`**, that detects all the "undeclared variable name" warnings produced by JSHint on the scripts in /src and /src/libs, and I have fixed all these warnings.

Is this script called by `make_dist` ?
Could be great to have such warning when generating `brython.js`.

**Comment by moepnse** [comment]
No problem, the main thing is that the errors are gone. It was fun to work a bit on Brython.

I agree with @denis-migdal. According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode, activating strict mode can speed up the execution of code.

Unfortunately, I couldn't find any benchmarks quickly.

**Pull request closed without merging**
