### PR TITLE
Package is a javascript reserved word, don't use it as variable name.

### PR DESCRIPTION
**Pull request by jonathanverner**
This is true only in strict mode; but I think we should rename it anyway to avoid possible future breakage.

### CODE REVIEW

**Comment by jonathanverner** [comment]
@PierreQuentel any thoughts on this?

**Comment by PierreQuentel** [comment]
Sorry, I completely missed this one.

I think I granted you admin rights so you can merge PRs, is it the case ?

**Comment by jonathanverner** [comment]
@PierreQuentel No problem, and it was not too important either :-) Yes, you granted me admin rights but I don't quite feel comfortable merging my own stuff in particular where I am touching parts which were not written by me in the first place... But you are right, this was probably a change which I could have merged myself...

**Comment by PierreQuentel** [comment]
For this kind of small change you can push changes directly, the only thing to take care of is that the built-in test suite passes without errors, and to run /scripts/make_dist.py to generate a new version of the generated scripts (brython.js, brython_stdlib.js etc.) and commit/push them

**Comment by meteozond** [comment]
Looks like [it is not strict](https://github.com/brython-dev/brython/blob/0a094c5ece27262cd0993730c750af0a2d9efbdc/www/src/py_import.js#L1134) again

**Pull request merged**
