### PR TITLE
Improve perfomance of getattr

### PR DESCRIPTION
**Pull request by redradist**
All tests are passed ;)

### CODE REVIEW

**Comment by schmave** [comment]
Could you quantify how much this changes the runtime on the various Brython benchmarks? https://github.com/brython-dev/brython/tree/master/www/speed/benchmarks

**Comment by schmave** [comment]
The dev server lets you run them locally: http://localhost:8000/speed

**Comment by redradist** [comment]
> 
> 
> The dev server lets you run them locally: http://localhost:8000/speed

On those tests it is not faster, it's the same !!
Speed increased for repeated accessing to the same attributes ... I think additional test is needed ...

**Comment by redradist** [comment]
In this pull-request seems like `$method_cache` is not needed anymore because it is part of global object cache ... but I leave it for future refactoring

**Comment by redradist** [comment]
@PierreQuentel Do you have question to this review ?
Maybe some comments or worry ?

**Comment by PierreQuentel** [comment]
I ran the speed tests (_speed/make_report.html_) with the current development version and with this PR on Firefox, here are the results I found:
```
                                      | current |  PR

simple assignment                     |      11 |   11
augmented assignment                  |      10 |   11
augmented assignment and list append  |     417 |  200
simple assignment to float            |     113 |  120
big integers                          |    3500 | 3810
build dictionary                      |     337 |  663
build dictionary 2                    |     143 |  134
set dictionary item                   |      85 |   83
build set                             |     582 |  536
build list                            |      47 |   42
set list item                         |      58 |   49
integer addition                      |     186 |  171
string addition                       |     126 |   56
cast int to string                    |     172 |  101
create function without arguments     |     455 |  450
create function, single pos. arg      |     423 |  376
create function, complex arguments    |     634 |  643
function call                         |     743 |  623
function call, complex arguments      |    1231 | 1079
create simple class                   |     622 |  532
create class with init                |     633 |  594
create instance of simple class       |     212 |  255
create instance of class with init    |    1001 |  981
call instance method                  |    1368 | 1477
------------------------------------------------------
MEAN                                  |     546 |  542
```
Some operations are faster with this PR, other are slower, and the mean value shows no difference. At the moment I don't see any compelling reason to merge this PR.

**Comment by redradist** [comment]
> 
> 
> I ran the speed tests (_speed/make_report.html_) with the current development version and with this PR on Firefox, here are the results I found:
> 
> ```
>                                       | current |  PR
> 
> simple assignment                     |      11 |   11
> augmented assignment                  |      10 |   11
> augmented assignment and list append  |     417 |  200
> simple assignment to float            |     113 |  120
> big integers                          |    3500 | 3810
> build dictionary                      |     337 |  663
> build dictionary 2                    |     143 |  134
> set dictionary item                   |      85 |   83
> build set                             |     582 |  536
> build list                            |      47 |   42
> set list item                         |      58 |   49
> integer addition                      |     186 |  171
> string addition                       |     126 |   56
> cast int to string                    |     172 |  101
> create function without arguments     |     455 |  450
> create function, single pos. arg      |     423 |  376
> create function, complex arguments    |     634 |  643
> function call                         |     743 |  623
> function call, complex arguments      |    1231 | 1079
> create simple class                   |     622 |  532
> create class with init                |     633 |  594
> create instance of simple class       |     212 |  255
> create instance of class with init    |    1001 |  981
> call instance method                  |    1368 | 1477
> ------------------------------------------------------
> MEAN                                  |     546 |  542
> ```
> 
> Some operations are faster with this PR, other are slower, and the mean value shows no difference. At the moment I don't see any compelling reason to merge this PR.

Okay, I will also check on me side ... thanks for feedback !!

**Comment by redradist** [comment]
@PierreQuentel 
> 
> 
> I ran the speed tests (_speed/make_report.html_) with the current development version and with this PR on Firefox, here are the results I found:
> 
> ```
>                                       | current |  PR
> 
> simple assignment                     |      11 |   11
> augmented assignment                  |      10 |   11
> augmented assignment and list append  |     417 |  200
> simple assignment to float            |     113 |  120
> big integers                          |    3500 | 3810
> build dictionary                      |     337 |  663
> build dictionary 2                    |     143 |  134
> set dictionary item                   |      85 |   83
> build set                             |     582 |  536
> build list                            |      47 |   42
> set list item                         |      58 |   49
> integer addition                      |     186 |  171
> string addition                       |     126 |   56
> cast int to string                    |     172 |  101
> create function without arguments     |     455 |  450
> create function, single pos. arg      |     423 |  376
> create function, complex arguments    |     634 |  643
> function call                         |     743 |  623
> function call, complex arguments      |    1231 | 1079
> create simple class                   |     622 |  532
> create class with init                |     633 |  594
> create instance of simple class       |     212 |  255
> create instance of class with init    |    1001 |  981
> call instance method                  |    1368 | 1477
> ------------------------------------------------------
> MEAN                                  |     546 |  542
> ```
> 
> Some operations are faster with this PR, other are slower, and the mean value shows no difference. At the moment I don't see any compelling reason to merge this PR.

I have tried to run speed tests with speed/index.html, but got the following error:
```console
Brython: 5.00
Traceback (most recent call last):
  File http://localhost:63344/brython/www/speed/index.html?_ijt=9cuuuhqp4p6440u4b359quvomc/__main__ line 62, in forward
    cpython_time = float(req.text)
ValueError: Could not convert to float(): '<!doctype html><title>404 Not Found</title><h1 style="text-align: center">404 Not Found</h1><hr/><p style="text-align: center">WebStorm 2020.1.2</p>'
```

**Comment by PierreQuentel** [comment]
I have no idea what this request with a query string starting with `_ijt=...` is. In all my tests I use the CPython `http.server` module.

**Pull request closed without merging**
