### PR TITLE
easily share code

### PR DESCRIPTION
**Pull request by kikocorreoso**
The PR adds some functionality to the editor that allows a user to share the code snippet with others just using a URL.

There is a new button called `share_code` where you can get a url. The code from the editor is included in the url so when you paste this url in the browser the editor will show the same code you are using.

Please, let me know if it is useful.

### CODE REVIEW

**Comment by PierreQuentel** [comment]
Hi Kiko,
Hope you and all your loved ones are well !

I understand the need for this feature, but I am not totally convinced to merge the PR : the query string is limited to 4096 bytes, so only short snippets could be sent this way. What is the advantage compared to sending the Python code inside a mail for instance ?

**Comment by kikocorreoso** [comment]
Hi, Pierre!

The same to you. Please, stay at home and save!!!

The url length depends on the browser: https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers Even less than 4096 bytes is recommended.

The only convenience is to just click an use instead of copying a snippet with the possibility to lose the format, having to open the editor, having to paste again on the editor,... I am thinking in tutorials for beginners where you can add a link and it will open an editor ready to run or to answer to some questions in the forums,... Newbies maybe do not know how to do it by themselves.

But you are right and it could introduce some problems for users on old browsers. Maybe a checkpoint to check if the url length is shorter than a limit before generating the url?

1. Write code in the editor.
2. click the 'share' button.
3. check if the final url is shorter than a limit.
4. if it is shorter generate a link. If it is larger not generate a link and warn the user about the problem.

Just let me know what do you think to close the PR or add some more code.

Again, please, #StayAtHome.

Thanks.

**Comment by PierreQuentel** [comment]
I have slightly modified your code, using the __`browser.widgets`__ package instead of the native browser prompt, and automatically copying the code in the clipboard. I have uploaded it to [brython.info](http://localhost:8000/tests/editor-kiko.html?lang=en). 

If code length is > 2048 an error message is sent; it allows code of a few dozens of lines, and should be safe for all browsers (including smartphone browsers, which are not mentioned in the stackoverflow discussion).

**Comment by kikocorreoso** [comment]
Thanks, Pierre.

Much pretty solution.

In Spain we are developing online resources for children (and adults) staying at home these days. So this could help to easily share resources in online courses and this kind of stuff.

Thanks again!!!

**Comment by PierreQuentel** [comment]
I have updated the editor at brython.info.

Thanks, and take care !

**Pull request closed without merging**
